### ISSUE TITLE
Create different language options

### ISSUE THREAD

**Issue by E1ite007** [V10lator/NUSspli#10]
Maybe add the possibility for multiple languages for the app, something simple as english, spanish, etc.

**Comment by GamesSanti** [comment]
I could help with the brazilian language.

**Comment by Carlitosnu** [comment]
I help in spanish language

**Comment by Mikumike1** [comment]
I can help for Italian

**Comment by Mikumike1** [comment]
I can help for the Italian language

**Comment by TotorRuns** [comment]
I could help with German

**Comment by V10lator** [comment]
@E1ite007 Would a simple .json file like this be sufficient?
```
{[
	"Press",
	"to download content",
	"to install content",
	"to generate a fake <title.tik> file,
	"for options",
	"or",
	"to exit",
	"Thanks to:      ",
	"Beta testers:   ",
	"WARNING:",
	"• Don't eject the SD card or the application will crash!",
	"• You're unable to exit while installing a game!"
]}
```

**Comment by E1ite007** [comment]
I imagine it should. The program loading a different .json to load a foreign language would be far easier to hardcode 'em to NUSspli. Of course, if the .json files would be missing the program would crash or something like it (unless it's still hardcoded to english as a backup) but NUSspli can generate them on the /wiiu/app/NUSspli folder or on /NUSspli on the root of the SD.
It would even make possible to add custom translations and more.

The translation of this .json to spanish would be.

```
{[
	"Presiona",
	"para descargar contenido",
	"para instalar contenido",
	"para generar un<title.tik> falso",
	"para opciones",
	"o",
	"para salir",
	"Gracias a:      ",
	"Beta testers:   ",
	"PRECAUCIÓN:",
	"• ¡No retirar la tarjeta SD o la aplicación crasheará!",
	"• ¡No es posible salir mientras se instala un juego!"
]}
```

Beta testers stay the same, because it's the common way to call them even in spanish. We don't use something as "probadores beta" 'cause it sounds strange.

**Comment by Carlitosnu** [comment]
Yes

**Comment by MaskedCat** [comment]
I don’t know if it is any help but I made a French version

{[
	"Appuyez",
	"pour télécharger du contenu",
	"pour installer du contenu",
	"pour générer un faux fichier <title.tik>", 
	"pour accéder aux options",
	"ou",
	"pour quitter",
	"Remerciments :      ",
	"Testeurs:   ",
	"ATTENTION:",
	"• n’éjectez pas la carte SD ou l’application va crash",
	"• Vous ne pouvez pas quitter pendant l’installation d’un jeu"
]}

**Comment by V10lator** [comment]
Thanks but that's just the home screen. There are way more things which need translation. Also I'm still planning the best possible implementaton (to be fair: I'm doing this with low priority) so adding translations right now isn't helping at all. Last your translation isn't even valid JSON (no key/value pairs but you can't even know the keys as again, the implementation is still in the planning phase).

**Comment by neph00** [comment]
I can help with polish translation.

**Comment by AmidoNewsInside** [comment]
{[
	"Aperte",
	"para baixar o conteúdo",
	"para instalar conteúdo",
	"para gerar um <title.tik> falso",
	"para opções",
	"o",
	"para sair",
	"Obrigado a:      ",
	"Beta testers:   ",
	"ATENÇÃO:",
	"• Não remova o cartão SD ou o aplicativo travará!",
	"• Não é possível sair durante a instalação de um jogo!"
]}

For Brasil Portuguese

**Comment by V10lator** [comment]
The following texts have been AI translated, so wee need human verification. Anyone up for reviewing them?

https://github.com/V10lator/NUSspli/blob/master/data/locale/Italian.json
https://github.com/V10lator/NUSspli/blob/master/data/locale/Russian.json

@yunes-0840 @MaskedCat @neph00 @AmidoNewsInside Pull requests for more languages welcome (just pull the .json files, I'll do the rest).

**Comment by V10lator** [comment]
Italian confirmed.

**Comment by neph00** [comment]
Hey,

what about polish language?
I can make this translation.

Pozdrawiam
Daniel


niedz., 28 sie 2022 o 17:31 V10lator ***@***.***> napisał(a):
