### ISSUE TITLE
Gets stuck when launching from HB

### ISSUE THREAD

**Issue by CristianOrtega97** [V10lator/NUSspli#101]
I tried to load the app.

I open HB from Channel and then the 1.90 version and it gets stuck![image](https://user-images.githubusercontent.com/14861982/166160098-4436e9e0-bb13-44a7-ae81-f37d7656361d.jpeg)

**Comment by Xpl0itU** [comment]
Use mii maker to launch NUSspli or any other homebrew

**Comment by CristianOrtega97** [comment]
I did and downloaded paper mario (wii version). However I get a black screen with sound and movement. Should I open another issue?
