### ISSUE TITLE
Nuuspli won’t let me download content on my usb, only on NAND

### ISSUE THREAD

**Issue by camiller-olivo** [V10lator/NUSspli#102]
![0CB63065-07D1-4DF7-8699-39D22CBC4DAC](https://user-images.githubusercontent.com/104743719/166174387-6d2a8807-4dae-4ce3-8f28-ee595fc788e4.png)

**Comment by Misunderstood-Wookiee** [comment]
Not a bug, try using another WUP installer because all of the WUP installers and my USB are detected on my Wii U, I am able to install WUPS to USB without issue so I reckon it is a more a problem with your USB.
