### ISSUE TITLE
Not installing big files

### ISSUE THREAD

**Issue by CristianOrtega97** [V10lator/NUSspli#104]
Tried installing directly. Downloading the title into SD and USB even with different storage and SD but here is the screen I get. I tried with a Half size title and I noticed that it only happened with big files

**Comment by CristianOrtega97** [comment]
Here is the screen error:

Version: 1.92
Title: Smash Bros Wii U

Will try to replicate with BOTW and also try with different SD and storage

**Comment by CristianOrtega97** [comment]
Screenshot![image](https://user-images.githubusercontent.com/14861982/166328448-8f4af226-a81e-41e0-aa51-4aa3c763098b.jpeg)

**Comment by CristianOrtega97** [comment]
Tried same steps with Breath of the wild and failed as well

**Comment by CristianOrtega97** [comment]
Tried to update sigpatches and tiramisu and still not working (I am not sure if it has something to do but I am just sharing).

**Comment by tjukkie** [comment]
Yes, I can confirm this happens to me too. "Large" installs seem to cause this. Don't know which size is ok and which isn't.

My drive is an 3.5 inch external powered drive. So it's not a usb hdd powered with an y cable through the WiiU itself.

**Comment by V10lator** [comment]
@CristianOrtega97 Duplication of #80
