### ISSUE TITLE
Entering wrong URL freezes the application

### ISSUE THREAD

**Issue by Roet-Ivar** [V10lator/NUSspli#11]
HOW: 

- Remove any nusspli config-file on the SD card to trigger the "enter URL option".
- Enter a faulty or partial URL that doesn't point to a valid target file

WHAT

- application triggers the goodbye screen and freezes

**Comment by V10lator** [comment]
These are actually two bugs:
1) NUSspli exiting when a wrong URL is used.
2) None-correct exiting.

The second one is weird as we can recreate it (exit by pressing B instead of HOME will trigger the exact same exit route) but it seems to exit just fine. So do you have a way to recreate this freeze?

**Comment by V10lator** [comment]
Nevermind, found both mistakes. :)

**Comment by Roet-Ivar** [comment]
Oh, that was fast, good job man!

**Comment by V10lator** [comment]
Version 1.9 doesn't use the title key site anymore.
