### ISSUE TITLE
bad downloads

### ISSUE THREAD

**Issue by kleffa** [V10lator/NUSspli#118]
I have several bad instalation titles, but only option to make them work is to delete and retry....
is very slow and disrupting let the wiiu all night dowloading one title, just to wake up and find "error, files may be corruted"

what if nuspli gets able to delete last intalling file, to download again and just avoid to download them all again and again?

**Comment by alokation2020** [comment]
i have the same error !

**Comment by DJZSwag** [comment]
I recommend you post in this issue; as this issue is most likely going to get closed because of duplication 
https://github.com/V10lator/NUSspli/issues/80

**Comment by V10lator** [comment]
What @DJZSwag said.
