### ISSUE TITLE
Support for Wii Pointer

### ISSUE THREAD

**Issue by DJZSwag** [V10lator/NUSspli#119]
This is self-explanatory, and this could go well with a GX2 interface.

**Comment by V10lator** [comment]
> could go well with a GX2 interface.

So this is a dup of #15 ? ;)

**Comment by DJZSwag** [comment]
I am aware of #15. I simply made this as a suggestion to the GX2 update (if it ever happens)

**Comment by V10lator** [comment]
We sure as hell will add pointer support when the GX2 update happens. None of the team has UI programming experience but we're getting better with SDL (that's what NUSspli is currently using for the simple/text based UI) and SDL should allow pointer support and stuff, too (like the homebrew appstore uses https://gitlab.com/4TU/chesto which in return uses SDL, for example).

BTW: Next time just add stuff like this as a comment to #15 . It won't get forgotten there like it will be in closed issues. No need to add pointer support as a comment now through as we have that on our radar alrady.
