### ISSUE TITLE
No works downloads

### ISSUE THREAD

**Issue by Carlitosnu** [V10lator/NUSspli#12]
Hi i'm downloaded NUSspli in the chanel version and not downloading.
I'm try in the homebrew launcher

Thank You

**Comment by V10lator** [comment]
Saw that just now, sorry. Could you try version 1.9 ? If that doesn't work could you try the DEBUG version in combination with https://github.com/dimok789/loadiine_gx2/blob/master/udp_debug_reader/UdpDebugReader.exe ? Just start the exe on your PC and NUSspli DEBUG on your Wii U while both are on the same network. No need to configure anything. Then handle the log file to me.

**Comment by V10lator** [comment]
Closing cause of no more replies. Reopen with the requested infos if still a issue.
