### ISSUE TITLE
Issue with NUSSpli

### ISSUE THREAD

**Issue by RMED24** [V10lator/NUSspli#128]
I've been using tiramisu and NUSSpli for some time with no issue. This morning I woke up to a surprise update, which is whatever. Well now I try to launch NUSSpli from the homebrew launcher, and a red screen pops up with the error message 'Either you're not using Tiramisu or your Tiramisu version is out of date'

What on earth would I do?

**Comment by V10lator** [comment]
Update Tiramisu.

To do this go to https://tiramisu.foryour.cafe/ and select at least Environments/Tiramisu/Base-Tiramisu. Download the package and extract it to your SD card overwriting existing files. Lastly reboot the Wii U.
