### ISSUE TITLE
Stops downloading randomly

### ISSUE THREAD

**Issue by GamesSanti** [V10lator/NUSspli#13]
Sometimes when using it justs stops downloading, is there anyway to fix this? Im using Haxchi.

**Comment by GamesSanti** [comment]
Rebooting the router seems like a temporary solution, but its still annoying.

**Comment by Souperman9** [comment]
Rebooting the router? Sounds like a problem with your internet connection.

**Comment by GamesSanti** [comment]
> Rebooting the router? Sounds like a problem with your internet connection.

My internet was fine, was in my pc the whole time, I had to give the program a internet error so I could download again

**Comment by GamesSanti** [comment]
It starts to download a file like "00000048.app" and it sometimes downloads exactly 10 kilobytes and stops downloading the file, so I restart the router, gave NUSSpli an error, pressed Y and it continues downloading, and its annoying doing that when the download speed is 4 megabits per second, and yes I know that V10lator is gonna improve download speeds.

**Comment by V10lator** [comment]
v1.14 detects and interrupts stalled downloads. Still sounds like something is wrong with your connection.
