### ISSUE TITLE
Tiramisu version error

### ISSUE THREAD

**Issue by guill3sm** [V10lator/NUSspli#130]
When i update to newest version ( v1.99 ) an error in the enviroment tiramisu jumps and says that i have an outdated version of it while tiramisu is on lattest version, i should reinstall nuspli directly?

**Comment by V10lator** [comment]
Show the version.json file from the root of your SD card, please.

**Comment by guill3sm** [comment]
acc. im unable to check that cuz is a friends problem ill close issue and reply when i have the version aviable; have a great day

**Comment by V10lator** [comment]
Allright, normally we don't do this here (go to Discord for support) but I'm pretty sure Tiramisu is outdated. The version.json file contains the Tiramisu version, so would proove it (and a missing version.json file would mean horribly outdated Tiramisu).

So tell your friend to go to https://tiramisu.foryour.cafe - select at least Environments/Tiramisu/Base-Tiramisu. Download the package and extract it to the root of the SD card overwriting existing files. Finally reboot the Wii U. Now all should work fine.
