### ISSUE TITLE
install error when trying to install from sd card

### ISSUE THREAD

**Issue by luklala2** [V10lator/NUSspli#142]
i opened nusspli and i was asked to update it i updated it and was gonna install some games from my sd card, when i did it i got install failed error and that also happens when using downloading method and i tried install on usb
the usb hdd works fine and it has y cable and the wii u can detect it the games installed on it works fine (it was installed using nusspli)
how to fix? i have latest tiramisu version with autoboot turned on

**Comment by V10lator** [comment]
What's the exact error message?

**Comment by luklala2** [comment]
it shows "Installation Failed, Files might be corrupt"

**Comment by AndresVoxd** [comment]
> Could you try to grab a syslog with https://raw.githubusercontent.com/wiiu-env/MochaPayload/master/source/ios_mcp/wupclient.py please? To do this open the file and edit the correct IP at line 29, then run it after recreating the issue (while the error screen gets shown).

**45391973** Is this ip the one I should use on my wiiu?

**Comment by Masamune3210** [comment]
....thats not a IP address

**Comment by AndresVoxd** [comment]
> ....thats not a IP address
> 
> A IP address will look like 192.168.1.somenumberhere

Oh...

Sorry! This ip: 192.168.178.23

**Comment by charliekempf** [comment]
I am getting the same error message. Trying to locally install a backup of Majora's Mask that I have already downloaded via NUSspli. Let me know if there is anything I can do to help.

**Comment by charliekempf** [comment]
Alright I ran the wupclient.py that you provided but I am not sure where the generated syslog is stored

**Comment by charliekempf** [comment]
Alright I'm assuming the 'syslog' is the terminal output of wupclient.py so I copied it to a txt file. It is attached below. Hopefully this is helpful
[syslog.txt](https://github.com/V10lator/NUSspli/files/9767582/syslog.txt)

**Comment by V10lator** [comment]
No idea why the log isn't formatted correctly and wihtout any newlines it's really hard to read but thanks anyway.

Could you try to remove at least the wiiload and ftp plugin from Aroma and retry, please?

To the others with the same issue: Are all of you on Aroma?

**Comment by luklala2** [comment]
update: its fixed i updated to the latest nusspli version and it worked

**Comment by V10lator** [comment]
@luklala2 Glad it works for you but there are more people with this issue, so let's keep it open untill we have more confirmation that it had been fixed. :)

**Comment by nchristopher** [comment]
I was having the same issue on Aroma, and I think it's because signature patches aren't implemented or aren't working for Aroma.

I placed this [signature patches](https://github.com/marco-calautti/SigpatchesModuleWiiU/releases/) module in `wiiu/environments/aroma/modules/setup/` and it seems to have fixed the issue.

**Comment by V10lator** [comment]
Closing cause I guess this has been fixed / no more reports incoming.
