### ISSUE TITLE
NUSspli only showing "Installation Failed, Files might be corrupt"

### ISSUE THREAD

**Issue by WiiPoint24** [V10lator/NUSspli#143]
I did delete splatoon (JP) and Splatoon (EU) Because they weren't working, what do I have to do?

**Comment by WiiPoint24** [comment]
Also it applies to anything I try to install

**Comment by V10lator** [comment]
Are you downloading through NUSspli or installing from some other source?

**Comment by WiiPoint24** [comment]
I am downloading it through nusspli

**Comment by V10lator** [comment]
To what storage medium are you downloading to (SD, USB or NAND) ?

**Comment by WiiPoint24** [comment]
SD and NAND (And they Both Fail)

**Comment by WiiPoint24** [comment]
And, my CFW is Tiramisu

**Comment by CarlosNunezMX** [comment]
I've same
Downloading from USB and install to USB.
Game downloading Cubeshift [0005000010213b00].
CFW: Aroma

**Comment by V10lator** [comment]
Could you try to grab a syslog with https://raw.githubusercontent.com/wiiu-env/MochaPayload/master/source/ios_mcp/wupclient.py please? To do this open the file and edit the correct IP at line 29, then run it after recreating the issue (while the error screen gets shown).

**Comment by V10lator** [comment]
Closing as a dup of #142 now. Please, please provide a log there.
