### ISSUE TITLE
Icons in the app showing as red X's

### ISSUE THREAD

**Issue by Breadbug21** [V10lator/NUSspli#150]
After updating to the newest version, several icons just show as red X's (for example, the region icons)

**Comment by V10lator** [comment]
HBL, Channel or Aroma?

**Comment by Visualwit** [comment]
I have like corrupted icons on my NUSspli channel, 1.117.

**Comment by V10lator** [comment]
Fixed with v1.118.

Thanks for reporting. :)

**Comment by Visualwit** [comment]
Wow, updated twice in one day!
