### ISSUE TITLE
Stuck at Splashscreen 

### ISSUE THREAD

**Issue by zortos293** [V10lator/NUSspli#152]
Hello i tried multiple versions of nusspli and it gets stuck on splash screen

[GeckoLog.txt](https://github.com/V10lator/NUSspli/files/9896240/GeckoLog.txt)
logs

Error initializinf filesystem << this is the error i get

**Comment by zortos293** [comment]
[GeckoLog.txt](https://github.com/V10lator/NUSspli/files/9896242/GeckoLog.txt)
other log file was empty

**Comment by V10lator** [comment]
Update Tiramisu or Aroma and try again with newest NUSspli, please.

**Comment by zortos293** [comment]
tnx that worked ;)
