### ISSUE TITLE
NUSspli update: File held open by another process

### ISSUE THREAD

**Issue by eku** [V10lator/NUSspli#157]
Self-updating the aroma WUG version from 1.113 to 1.119 results in red screen with error
```Fehler beim verschieben der Datei: File held open by another process```

Probably NUSspli wants to tell me that the file is being executed and therefore not overwritten.

After that error, the WUHB icon is gone from the `System Menu`.

Let me know if you need further informations.

**Comment by V10lator** [comment]
Thanks for the report. This is actually an Aroma bug (file telling it is held open by another process after it had been deleted already) and 1.119 contains a workaround for it already.
