### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by Exorcism0666** [V10lator/NUSspli#158]
In the "base.json" file line 103: "detete" instead of "delete".

**Comment by luissilva1044894** [comment]
All files have this typo.
If no one fixes it, I'll do a PR tonight.

https://github.com/V10lator/NUSspli/blob/dc72b454a1fa153e65a20477981313a60271d4f8/data/locale/base.json#L103
https://github.com/V10lator/NUSspli/blob/dc72b454a1fa153e65a20477981313a60271d4f8/data/locale/Brazilian%20Portuguese.json#L122
https://github.com/V10lator/NUSspli/blob/dc72b454a1fa153e65a20477981313a60271d4f8/data/locale/German.json#L103
https://github.com/V10lator/NUSspli/blob/dc72b454a1fa153e65a20477981313a60271d4f8/data/locale/Portuguese.json#L122
https://github.com/V10lator/NUSspli/blob/dc72b454a1fa153e65a20477981313a60271d4f8/data/locale/Spanish.json#L121
