### ISSUE TITLE
Couldn’t save confit file! Your SD Card might be write locked. 

### ISSUE THREAD

**Issue by YoungFox88** [V10lator/NUSspli#161]
Hi So I have a Wii u and When I download a game it say Couldn’t save confit file! Your SD Card might be write locked. But my sd card is not locked so what dose This mean and when a click any button it say Permission error (read only file system?)

**Comment by Masamune3210** [comment]
It means that for whatever reason, NUSspli failed to write to the sd card, either because of file system issues, card failure, a bug, or any other state that would cause writing to the SD card to fail

**Comment by Masamune3210** [comment]
Checking the filesystem for damage would be a good first step

**Comment by YoungFox88** [comment]
Thank You I Think I fix it Thanks you

**Comment by Masamune3210** [comment]
No problem
