### ISSUE TITLE
Error while opening game

### ISSUE THREAD

**Issue by Helpo-beep** [V10lator/NUSspli#166]
i opened the game and it said "unable to use the software
the nintendo network id used to purchase it has been deleted"
it did this everytime.

**Comment by Xpl0itU** [comment]
You need to have sigpatches installed, check wiiu.hacks.guide for more info

**Comment by Helpo-beep** [comment]
i have them installed, it still does that @Xpl0itU

**Comment by Helpo-beep** [comment]
@V10lator aroma but if i load tiramisu it's the same

**Comment by Helpo-beep** [comment]
i tried again and it worked!

**Comment by Fau57** [comment]
im having the same issue and have tiramisu installed and have the sig patches file in the modules/setup folder. is there something i missed during install?
