### ISSUE TITLE
NUSspli "Don't run the EnvironmentLoader twice."

### ISSUE THREAD

**Issue by Setayo** [V10lator/NUSspli#168]
Hi, new to homebrew WiiU and I have been trying to get the HBL NUSspli to run on Tiramisu (I have verified it's the latest version and overwritten the SD card with the latest download from their website) however whenever I run NUSspli from the HBL it comes up with the screen "Don't run the EnvironmentLoader twice. If you want to open the Homebrew launcher, launch the Mii Maker instead."

No other errors are present and this happens every time I attempt to open NUSspli.

If any more information is required or any videos/screenshots then I'll do my best to collect these for you.

**Comment by Setayo** [comment]
Update: It is now only doing this intermittently, sometimes I'll have to reboot the WiiU and it will run fine, other times this will appear. Doesn't seem to be any way of making this occur consistently

**Comment by V10lator** [comment]
Please make sure both, NUSspli and Tiramisu are up 2 date. Also make sure to start NUSspli from thr HBL injected into Mii Maker.

In case none of this helps check your card with https://3ds.hacks.guide/h2testw-(windows).html , please.

**Comment by Setayo** [comment]
The issue i had was my sd card wasnt mounting properly to my ubuntu laptop... I tried this all again with the Windows PC and it's sorted.. Really sorry for this. On ubuntu it showed that the files were writing and making changes, however it was doing nothing.

**Comment by V10lator** [comment]
> On ubuntu it showed that the files were writing and making changes, however it was doing nothing.

It probably did something, you just didn't unmount the card properly, so the I/O operations where still in RAM. Every operating system does this to speed up I/O.
Like on Windows there should be something like "safely unmount the card" at the taskbar, so use that next time and disconnect the SD card only after it told you it's good now.

Another option would be to mount the card in sync mode, so the RAM cache doesn't get used but all I/O operations are performed directly on the card but that's not recommended and a bit more complicated to setup.
