### ISSUE TITLE
"USB Error" while installing to USB

### ISSUE THREAD

**Issue by eku** [V10lator/NUSspli#17]
My console has two hard drives. The second one is FAT32 formatted and hidden by [`UStealth`](https://github.com/rudism/ustealth.sh), so the console actually ignores them. But not when installing via `NUSspli`. This causes a USB error. If I remove the second hard disk, the error is gone. But it's annoying if you have to think about it every time and have to unplug the hard disk and then plug it in again.

**Comment by eku** [comment]
NUSspli-1.18-ALPHA1-HBL-DEBUG works for me. Thanks.

**Comment by V10lator** [comment]
So it will be fixed in 1.18. Thanks for reporting and testing. :)
