### ISSUE TITLE
NUSspli not working on Aroma

### ISSUE THREAD

**Issue by LeoMassaFM** [V10lator/NUSspli#172]
Downloading and installing things works as intended, but when I try to launch the games I downloaded, my Wii U displays a message that the "Nintendo Network ID" that downloaded the games has ben deleted. What do I do? I am using the latest version of NUSspli and my homebrew environment is Aroma.

**Comment by nerdboy21** [comment]
This doesnt work for me :(

**Comment by Dan-Ok-2** [comment]
Didn't work for me either, does it matter if I use a Pretendo Id instead of the regular one?
