### ISSUE TITLE
couldn't load config files

### ISSUE THREAD

**Issue by Lighteroff** [V10lator/NUSspli#173]
hello ineed help beacause i have a hacked nintendo wii u and when i launch NUSspli i got the message error in the title of this thread. thanks you for answering^^

**Comment by Xpl0itU** [comment]
Your SDCard might be write locked, check that

**Comment by Lighteroff** [comment]
Nope it's not i verified a few Times

**Comment by V10lator** [comment]
The card loves to writelock itself. Please see https://gbatemp.net/threads/nusspli-install-content-directly-from-the-nintendo-update-servers-to-your-wii-u.566055/post-10028855 for more informations and solutions.

Also test with something like FTP that you are able to create files on the card, please.

**Comment by Lighteroff** [comment]
Ok thanks, i'll check that later and Come back tell you what's the results. Thanks for the solution cya

**Comment by Lighteroff** [comment]
> The card loves to writelock itself. Please see https://gbatemp.net/threads/nusspli-install-content-directly-from-the-nintendo-update-servers-to-your-wii-u.566055/post-10028855 for more informations and solutions.
> 
> Also test with something like FTP that you are able to create files on the card, please.

Hey i tested the solution right now but it don't work. Still get the "couldn't load config files" but i don't have any other error messages.

**Comment by V10lator** [comment]
What happens when you try to create a file with FTP?

What NUSspli version are you using?

**Comment by Lighteroff** [comment]
Everything Is working well when i try to create a file by the FTP but when i try to put something in my pc to my wii u by the FTP, most of the file i'm transfering got an error and can't be move ANYMORE. Concerning the version of nusspli, it's the 1.37 version.

**Comment by V10lator** [comment]
1) Sounds more like an issue with the SD card than with NUSspli.

2) 1.37 ist pretty old. Update to latest (1.125 at the time of writing), please.
