### ISSUE TITLE
how do i go to dlc tab

### ISSUE THREAD

**Issue by txnystqrk** [V10lator/NUSspli#178]
tell me

**Comment by Masamune3210** [comment]
Demanding things tends to not get the answer you want, also this isn't a help forum

**Comment by txnystqrk** [comment]
> Demanding things tends to not get the answer you want, also this isn't a help forum

how the fuck was i demanding you little cracker that snorts cum and candy powder, your the fucking equivelent of meth if it was human

**Comment by txnystqrk** [comment]
boom

**Comment by luissilva1044894** [comment]
Why u so toxic while being a dumb fuck who can't even try pressing buttons? 

As Masamune said, it's not a help form and no one is obligated to teach u how to use a Wii U. It's not how Github issues are works. I'm not V10lator, but I guess your answer is: GET FUCK OUT HERE.

**Comment by Masamune3210** [comment]
Reported
