### ISSUE TITLE
Homebrew launcher outdate

### ISSUE THREAD

**Issue by Mikumike1** [V10lator/NUSspli#18]
I downloaded super smash bros for wii u but when i try to install it it tells me that the homebrew launcher is outdate, can you help me? Thanks! (Sorry if my english sucks but i'm italian)

**Comment by Mikumike1** [comment]
Please help me @V10lator

**Comment by ThatFruedDued** [comment]
@Mikumike1 The temporary way I solved this issue (I have the same issue) is by downloading the title with NUSspli and installing it via WUP Installer or another similar tool. Really hope @V10lator fixes this soon.

**Comment by V10lator** [comment]
Please make sure you're either using the channel version or are launching the RPX file from https://github.com/GaryOderNichts/homebrew_launcher/releases/tag/v2.1_fix

**Comment by V10lator** [comment]
I'll close this now as nobody replies anymore. Also Aroma CFW is just around the corner and with it the HBL version will be opsolete.

In case this error affects you and the HBL update doesn't help feel free to reopen this issue.
