### ISSUE TITLE
Nintendo Account ID deleted issue

### ISSUE THREAD

**Issue by nohyper** [V10lator/NUSspli#180]
Every time I try to load a game it just says this software cannot be used. It also says to reinstall at the wii shop. Please help
![image](https://user-images.githubusercontent.com/91564539/215257442-9a96216e-4bac-496e-8e45-08f392b33193.jpg)

**Comment by V10lator** [comment]
You're missing sigpatches. Anyway, use Discord or GBATemp for support requests, please.
