### ISSUE TITLE
Error when try to install from USB to NAND

### ISSUE THREAD

**Issue by coolguy9304** [V10lator/NUSspli#183]
I have an issue. When I try to install a game (that take up more then few gb) from USB stick to NAND, the error appears: Installation failed! Possible USB failure. Check your drivers power source. Also files might be corrupt.
(my usb stick is 8gb only)
After this error, the game file is deleted

**Comment by V10lator** [comment]
What NUSspli version are you using?

**Comment by V10lator** [comment]
Closing cause of no more reply.
