### ISSUE TITLE
I can't open the app when my wii u has a conected USB

### ISSUE THREAD

**Issue by WolfTGamerUwU** [V10lator/NUSspli#19]
I have version 1.17.
The problem I have is that when a USB is connected, when I open the application I get the error "199-9999". Is the problem that I am doing something wrong or is it directly a bug?

(If I have written this in the wrong place, sorry for the inconvenience)

**Comment by Casuallynoted** [comment]
I've noticed the same thing here. Not sure why it's happening.

**Comment by eku** [comment]
Could this have the same reason as #17?

**Comment by V10lator** [comment]
Please test if this fixes your issue:
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.18-ALPHA1-Aroma-DEBUG.zip
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.18-ALPHA1-Channel-DEBUG.zip
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.18-ALPHA1-HBL-DEBUG.zip

**Comment by V10lator** [comment]
Please reopen if this is still a issue.
