### ISSUE TITLE
Network error: couldn't connect to server

### ISSUE THREAD

**Issue by vgiamp10** [V10lator/NUSspli#195]
i checked everything but i can't find the problem where it is, so im leaving this thing to have an explanation for this error

**Comment by V10lator** [comment]
Could you take a picture of the error screen and upload it here, please?

**Comment by kleonm280** [comment]
Hii, I have this problem 
![IMG_20230416_224616](https://user-images.githubusercontent.com/130954500/232377969-80ba8842-da80-451f-904e-f5aa35755ccb.jpg)

**Comment by V10lator** [comment]
@kleonm280
1) Don't derail bug reports.
2) No support for such horribly outdated versions as the one you're using: Update to latest release.

**Comment by V10lator** [comment]
Closing cause of no more reply.
