### ISSUE TITLE
DLC does not work

### ISSUE THREAD

**Issue by Gauley123** [V10lator/NUSspli#197]
I tried downloading DLC for Mario Kart 8 (EU) and it says
There is an error in the add-on content data.
Go to Data Management in System Settings to delete the add-on content.

**Comment by Gauley123** [comment]
Nevermind, i didnt have sigpatches module in aroma. My mistake

**Comment by SirenGlitch** [comment]
Which sigpatches module did you use? [V10lator/SigPlugin](https://github.com/V10lator/SigPlugin)? It's the only one I can find for Aroma

**Comment by haha-goodone-lol** [comment]
https://github.com/marco-calautti/SigpatchesModuleWiiU
