### ISSUE TITLE
Couldn't load config file!

### ISSUE THREAD

**Issue by supreme-idiot** [V10lator/NUSspli#20]
What can I do if Couldn't load config file appears? PLS HELP!

**Comment by V10lator** [comment]
Please check that your SD card isn't write locked.

**Comment by V10lator** [comment]
Please reopen if this is still a issue.

**Comment by supreme-idiot** [comment]
No thank you, I’m quite stupid and had the card blocked, actually, THANKS A LOT FOR NUSSPLI, ITS AWESOME.

Do you recommend me any title ID list?

Enviado desde mi iPhone

**Comment by V10lator** [comment]
> Do you recommend me any title ID list?

https://wiiubrew.org/wiki/Title_database is what NUSspli uses internally.

**Comment by supreme-idiot** [comment]
Do you know why when I open a wii title it just goes black screen. THANK YOU SO MUCH BRO FOR THE NUSSPLI

Enviado desde mi iPhone
