### ISSUE TITLE
SSL error 

### ISSUE THREAD

**Issue by Breezyxbx** [V10lator/NUSspli#200]
ever since i updated to the new version 1.131 i’ve been getting an error that says
SSL error:
      Verification failed!
check your Wii Us date and time settings 

i went to check everything was correct but i’m still getting an error is there any possible way to fix this error

**Comment by V10lator** [comment]
Do what it sais and check your Wii Us date and time settings.

**Comment by Breezyxbx** [comment]
i check date and time but i’m still getting SSL error
