### ISSUE TITLE
Instalation failed

### ISSUE THREAD

**Issue by AlejoRo** [V10lator/NUSspli#201]
Hi, I am getting this error when installing games. I have installed games that take up to 1.65GB and everything works as it should, but when I want to download games that take more space, I get this error during installation:

![Error](https://user-images.githubusercontent.com/66074495/234181207-a592b66a-9cd6-4801-b8fd-78a7bc4f02b0.jpg)

I have already tried with versions 1.125, 1.30 and 1.31.

**Comment by V10lator** [comment]
Check your hard drives power source.
