### ISSUE TITLE
Nusspli installation failed

### ISSUE THREAD

**Issue by Weejew** [V10lator/NUSspli#204]
I've been downloading games to my portable hardrive from nusspli I have a y cable conect to wii u but all of a sudden it says "installation failed possible usb failure check your drives power source files might be corrupt". When I download to the nand wii u hard drive it works but when I switch it to me portable hardrive it comes with that error I even reinstalled nusspli but I still get that error can anyone help me 
![20230505_095355](https://user-images.githubusercontent.com/132750992/236650708-d1282818-48c9-4396-9c7f-06657cb1cbb4.jpg)

**Comment by V10lator** [comment]
1) Don't spam your question everywhere (two posts on GBATemp, PMing me on GBATemp and this here).
2) This is for bug reports, not for support questions.
3) Do what has been suggested elsewhere already. So try a better power source and/or another HDD.

**Comment by Weejew** [comment]
Alright mate calm down
