### ISSUE TITLE
Games installed on Tiramisu does not work on Aroma

### ISSUE THREAD

**Issue by 1vb-iristr** [V10lator/NUSspli#206]
When I boot the game using Aroma, it gave me this error, but it was not the case for when I boot with Tiramisu.

Any reasons why this is the case?

![image](https://github.com/V10lator/NUSspli/assets/84076556/a39aea5d-ce9a-40b7-a275-7c1a90ee482b)

**Comment by 1vb-iristr** [comment]
+ I tried installing the games on both environments, Tiramisu and Aroma, and the games on Tiramisu works fine, not the case for Aroma.

**Comment by Xpl0itU** [comment]
You need to copy the sigpatches to the aroma folder
