### ISSUE TITLE
corrupted archive

### ISSUE THREAD

**Issue by dolfhd** [V10lator/NUSspli#209]
when i install a program in 99 percent it says corrupted archive please look at the USB or the AC

**Comment by V10lator** [comment]
Could you give more informations, please? Like are you downloading to SD or USB?

Beside that, to all beta testers: It seems there's a spike of such reports lately. Is anyone of you able to recreate this? In other words: Do we have the slightest sign of this beeing more than user error?

**Comment by dolfhd** [comment]
i am using USB, i didn't see anybody with that error. installing super smash bros it hapens this error

**Comment by V10lator** [comment]
Thanks. I'll do some mass testing next days (on two Wii Us simultaneously) and also I hope beta testers will try to recreate this, so we hopefully get to the root of it fast.

In the mean time: Which Super Smash Bros version are you trying to install (EUR, USA or JAP) ? Also do downloads to SD or NAND work fine?

**Comment by dolfhd** [comment]
btw it happens with every game that is bigger than 1GB, i install EUR games, i dont have enough space in my SD to try it. Sorry

**Comment by dolfhd** [comment]
V10lator can i help with anything?

**Comment by V10lator** [comment]
@dolfhd I'm i'll right now, so don't feel good enough to start the mass testing here. DM me in case you want to help and I'll tell you what needs to be done.

**Comment by alengamer** [comment]
Im having the same issue to

**Comment by dolfhd** [comment]
No i tal to you in discord

**Comment by alengamer** [comment]
Well first i tried to downloaf paper mario color splash but that did not work then i tried  download some random games and that did not work all they said is files might be corrupt

**Comment by alengamer** [comment]
Sorry for misspelling

**Comment by V10lator** [comment]
@alengamer Is this only when downloading to SD or also when downloading to USB or NAND?

**Comment by Okanos-2845** [comment]
At least in my case, it also happens when tryng to download to the USB, while before the update it did not

**Comment by alengamer** [comment]
Sd

**Comment by alengamer** [comment]
When do you think you will get this fixed

**Comment by juliousrobins** [comment]
I'm trying it rn on Wii through tiramisu Homebrew ill update if it works :)

**Comment by alengamer** [comment]
Could we install the older version for it to work

**Comment by juliousrobins** [comment]
it worked, but today when I opened the app it said it needed an update and I pressed instal and there was an error 
and the app disappeared

**Comment by alengamer** [comment]
Some games work and some games dont??

**Comment by alengamer** [comment]
Ok why do you keep releasing nuspil

**Comment by juliousrobins** [comment]
testing possible fixes I'm guessing @alengamer

**Comment by V10lator** [comment]
Next one spamming this bug report with useless questions will get banned.

**Comment by V10lator** [comment]
Closing as nobody is able to confirm that this happens with downloads to SD or NAND, so the error message is most likely correct and this is a USB issue like underpowered HDD.
