### ISSUE TITLE
"The Nintendo Network ID used to purchase this game has been removed" whenever getting Wii U games

### ISSUE THREAD

**Issue by In4init3** [V10lator/NUSspli#212]
I might just be terribly stupid, but this is an issue i am having

**Comment by V10lator** [comment]
We have a FAQ (visible at GBATemp and Discord) for a reason.

**Q**: The games I downloaded/installed through NUSspli won't run, giving either error code 199-9999 or telling the NNID used to purchase the software had been deleted. Why?
**A**: In case you're on Tiramisu you didn't follow the official guide ( https://wiiu.hacks.guide/ ). In case you're on Aroma download sigpatches from https://github.com/V10lator/SigpatchesModuleWiiU/releases and put the 01_sigpatches.rpx file to `/wiiu/environments/Aroma/modules/setup` on your SD card.

**Comment by DuZzz-imsleeping** [comment]
I have the sigpatches file but it's still giving the error
