### ISSUE TITLE
Can't Update from Wii U

### ISSUE THREAD

**Issue by juliousrobins** [V10lator/NUSspli#213]
Updating this from my Wiiu doesn't work for me so I gotta go back here and replace it after each update

**Comment by V10lator** [comment]
What's the error?

**Comment by juliousrobins** [comment]
I don't remember. once I get back from doing something in like 3 hours I'll try again and I'll see. sorry

**Comment by juliousrobins** [comment]
oops I completed it sorry

**Comment by alengamer** [comment]
Its still not working need some help?? The good thing is its working on some games

**Comment by juliousrobins** [comment]
https://github.com/V10lator/NUSspli/assets/135386702/31e519fb-f24d-4b9e-8499-9f89fc681c71

### this is a video of it happening

**Comment by V10lator** [comment]
Should be fixed with v1.136.
