### ISSUE TITLE
Bring Haxchi/Mocha support back

### ISSUE THREAD

**Issue by BedroQuendo** [V10lator/NUSspli#216]
Dear devs,
Buy a $6.99 rope. Why? Watch these update catalogs:
"Further improvements to overall stability and other ******minor adjustments******" We kywhat you did. You're another one who just killed support of something good for Haxchi users and now idk what was the last version to support Haxchi/Mocha.
You think it's cool to migrate trough a newer enviroment that it's far from finished? What is this? Michaelsoft? I hacked my Wii U like a couple of days before Tiramisu was announced (late 2021) and yet y'all bring no fucking mercy to give just *a tiny bit* of support to me and along of a few others.
What a big fuck you to everybody's effort to finallly jailbreak their console (because it wasn't that easy), even if it costs 7 dollars because of a DS game. We don't care. Suck my taint.

**Comment by swaggio7** [comment]
Bro, use Aroma for god sake, it's a monumental upgrade from Haxchi. You are acting like a Karen. Also, the Wii U is pretty easy to hack and migrate, even with Haxchi.

**Comment by V10lator** [comment]
@swaggio7 To be fair Aroma has some downsides when compared with Haxchi but Tiramisu don't have.

The OP just wants to rage cause he payed  $7 and now sees that it would have been better to not pay. He assults the devs, he says that our changelogs have no technical reasons but are there to distract the Haxchi support only and stuff like that... No need to argue with that kind of guy: He has been banned from our GitHub and all that's spreading from here to our Discord gets deleted ASAP. So just let this bug report rot... ;)
