### ISSUE TITLE
[nitpick, non-urgent] Repository enhancements to consider

### ISSUE THREAD

**Issue by RayBeard** [V10lator/NUSspli#217]
Not urgent, but I wanted to offer some suggestions that might make your lives a little simpler and help to make some of your release updates a little more obvious to folks who are browsing.

Consider using Conventional Commits 
https://www.conventionalcommits.org/en/v1.0.0/

And a semantic release github action
https://github.com/marketplace/actions/action-for-semantic-release

(Or something similar that fits your workflow. I hear good things about conventional changelog too, for example!)
https://github.com/conventional-changelog/conventional-changelog

There are a dozen different ways to address this and most of them should actually lower your workload in the long run!

Right now the release notes for the project are pretty barebones, but your commit content is good enough to make the crossover. If you use conventional commits and combine that with semantic releasing, it'll more or less generate release notes for you, so that they aren't so opaque.

At the moment it's quite challenging to work out (from an external perspective) what fixes went into which release  without going into the complete commit history and that can be useful information!

Hopefully you take this in the vein it is intended; Love the work y'all have going here and I'd love to have a simpler time browsing through what has already been addressed in the releases =]

**Comment by V10lator** [comment]
Done (credits to @Xpl0itU ).
