### ISSUE TITLE
Create Limitations to Erase Titles

### ISSUE THREAD

**Issue by TakeSora25** [V10lator/NUSspli#218]
I Dont know where to say this, but here is a good place i think...
The Adition to erase titles are GREAT, you dont need a gamepad anymore if you need more space in the USB... But, when i see. you can Erase... Almost Everything (Health and Safety Information app for example) and that can brick a console Easily... Soooo... You can ¨Hide¨ that important apps from the list???
Thanks For your Attention...

**Comment by juliousrobins** [comment]
I was thinking the same thing... and I also think that this would be a great idea to implement :)
