### ISSUE TITLE
SSL Context not set

### ISSUE THREAD

**Issue by buffaloddp** [V10lator/NUSspli#219]
to open the nusspli software has a bug that is not possible to click y to open , I have to click y and b multiple times.

![352791732_642658044048641_8873746335809196537_n - Copie](https://github.com/V10lator/NUSspli/assets/136626805/fb290619-207a-43ab-b7f2-55546906e577)
![352791732_642658044048641_8873746335809196537_n](https://github.com/V10lator/NUSspli/assets/136626805/caf6c68d-53f3-4ec9-a588-c195196d6564)

**Comment by Xpl0itU** [comment]
English please

**Comment by buffaloddp** [comment]
Good morning, No one speaks French here, it will be easier for me
To go to tiramitsu, I have to put the memory card in the console, it's not possible to do it without a memory card and if requiring a memory card is the size of the card 512MB enough?
Then I go to mii editor To open software, nusspli and others. and had WUP install GX2, but I no longer have it. So I went to homebrew and clicked on the software, I don't see the software coming back.
AND also to open the nusspli software has a bug that is not possible to click y to open , I have to click y and b multiple times. A Not another solution to make it easier. and also have the latest update.
for the search for games is that we can find the games of all the consoles and also custom games example a mario kart with maps created by fans .. and also how to download the games on an external hard drive.

And that's about what save mii and the software to play with Bluetooth controller, can we play with which controller and also play with usb controllers?

the photos are above on the first message in French

**Comment by V10lator** [comment]
> No one speaks French here
Not to my knowledge, no. We have germans, spain speakers, maybe even some chinese but no french, sorry.

> is the size of the card 512MB enough?
Depends. For just homebrew it might but if you want to download with NUSspli to it it might not be enough. In this case it also depends on your USB size.

> had WUP install GX2, but I no longer have it. So I went to homebrew and clicked on the software, I don't see the software coming back.
I guess there's some translation error as this doesn't make any sense to me.

> AND also to open the nusspli software has a bug that is not possible to click y to open , I have to click y and b multiple times.
Update to latest NUSspli version and check your Wii Us Date and Time settings.

> have the latest update.
The NUSspli error screenshots are pretty blurred but I can say for sure that they aren't from latest version.

> for the search for games is that we can find the games of all the consoles and also custom games example a mario kart with maps created by fans
NUSspli downloads directly from Nintendos servers. We can't add any content.

> how to download the games on an external hard drive.
You can download to a Wii U formatted harddive only.

**Comment by buffaloddp** [comment]
Ok, too bad no French here. Has by me :)

V10 Lator thank you for answering me and that you can answer me again, maybe with images or go

the sd card I just want to put the software needed to be able to install software to download the games, and download the games to hard disk. and how to do in the list of games and dlc?

to say that hard what is a harddive AND how to do it?

and how to update the software

the photos are not all blurry, that the red photo is where we open nusspli but a bug must be applied several times on y and b no other easier way?

and you can only download nintendo games with nusspli, so the nes, super nintendo, all game boy, game cube, n64 all versions of ds news 3ds 2ds the wii and the wiiu not the switch.

and how to play other console games not nintendo
En savoir plus sur ce texte sourceVous devez indiquer le texte source pour obtenir des informations supplémentaires
Envoyer des commentaires
Panneaux latéraux

**Comment by V10lator** [comment]
> the sd card I just want to put the software needed to

512 MB will be more than enough for this.

> what is a harddive

Hard disc or however you'll call it. A mechanical, spinning disc.

Anyway, note that this is a place for bug reports, not for support. For support go to https://gbatemp.net/threads/nusspli-install-content-directly-from-the-nintendo-update-servers-to-your-wii-u.566055/ or https://discord.gg/B8ZBd6mrnV please.

**Comment by Masamune3210** [comment]
The error, btw, is SSL Context not set, I could make it out because mine is doing the same thing and it was handy to cross reference since I haven't had the time to look into it yet lol

**Comment by V10lator** [comment]
@Masamune3210 Could you upload a better picture of the error screen, please?

**Comment by buffaloddp** [comment]
Good morning
the sound software on an 8gb sd card, I have to test on a smaller sd card to see 512mb. Because believe has a capacity to respect.

and say that external hard it all works and how much do you play a wiiu game, the nintendo console before the games are less heavy

and for my other questions?

and thank you for your line but there is no English in French and also French on discord?

**Comment by Masamune3210** [comment]
> @Masamune3210 Could you upload a better picture of the error screen, please?

Gladly, but it will have to wait until I get home from work later today

**Comment by V10lator** [comment]
Cleaned this up a bit.

@buffaloddp Again: For support go to https://gbatemp.net/threads/nusspli-install-content-directly-from-the-nintendo-update-servers-to-your-wii-u.566055/ or https://discord.gg/B8ZBd6mrnV please.

**Comment by Masamune3210** [comment]
> @Masamune3210 Could you upload a better picture of the error screen, please?

![IMG_20230616_142135.jpg](https://github.com/V10lator/NUSspli/assets/1053504/b123ed39-c24e-4c1f-99ad-c272106c5d91)

**Comment by Masamune3210** [comment]
@V10lator, just in case replying didn't give you a notification

**Comment by Masamune3210** [comment]
It stays on this for a while, only to eventually flicker to blue and then come back to this. It just does this on repeat until the error is acknowledged

**Comment by Masamune3210** [comment]
I stared at the screen long enough to figure out what the blue flicker was, its the normal screen it shows on boot where its listing all the things its checking, where it says stuff like I/O Thread initialized

**Comment by Masamune3210** [comment]
Trying to download anything goes through most of the download only to fail eventually with a network error stating curl_easy_preform return non-error value 18, and then seemingly by itself pick back up and finish the download. The downloaded title works just fine, at least the one I tested did

**Comment by V10lator** [comment]
@Xpl0itU You where right, it's really error 89... 🤯

I'm still a bit distracted but do you thing it's worth opening a issue upstream? Cause: `For internal use only, will never be returned by libcurl`.

**Comment by Masamune3210** [comment]
Honestly, if its possible to just suppress the error screen from being shown for that particular error, it might be better in the long term, at least for your sanity so that people don't flood in with reports of it. Like i said, the actual download and installation worked fine for me.

**Comment by V10lator** [comment]
@Masamune3210 Looking at your screenshot again you're using a horribly outdated NUSspli version known to be buggy as hell. Same for the OP.

So retest with newest NUSspli version (1.136 at the time of writing), please.

**Comment by Masamune3210** [comment]
I kind of figured that was likely the case, like I said I hadn't really had the time to look into it much and was just setting up Aroma on a whim when I noticed the error. After I get out of work today I will update and let you know.

**Comment by V10lator** [comment]
@Masamune3210 Alright, thanks. Just keep in mind that what fails here is the auto-update check, so you need to update manually (by simply replacing the .wuhb file on the SD card).

**Comment by Masamune3210** [comment]
Sorry it took so long to get back to you, the latest version does indeed not suffer from this issue.

Off-topic, but the thing that caused all my confusion when it comes to how I ended up running a super old version is a combination of thinking that I already had a wuhb of NUSspli on the sd card when I didn't and mistaking an old channel install as one since Aroma makes it not super easy to tell the two apart outside of going into Data Management and seeing if the channel shows up or not.

**Comment by buffaloddp** [comment]
Hello, So if you understand the messages above you know we have the latest version of NUSspli, we no longer have the problem of pressing several y and b to return. But how to do the latest update? if there is a file to replace or click on something tell me step by step what to do?

and also get the wup app install gx2

and also step by step how to download games to external hard drive

?

**Comment by Masamune3210** [comment]
If you are using the channel, delete it using data management. Make sure you are on latest cfw and then just drop the wuhb file from releases into anywhere in the WiiU folder on your SD card
