### ISSUE TITLE
buy you a beer

### ISSUE THREAD

**Issue by x-FBi** [V10lator/NUSspli#222]
Is there a way to donate and buy you a beer or coffee?

Can we add DLC to download options when we like a game, much like the update option?

**Comment by V10lator** [comment]
Sure thing: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XLZ5VV3N4T3CS

Anyway, this place is for bug reports, not for such questions, so for further questions hop to GBATemp ( https://gbatemp.net/threads/nusspli-install-content-directly-from-the-nintendo-update-servers-to-your-wii-u.566055/ ) or Discord ( https://discord.gg/B8ZBd6mrnV ), please.

Also it would be nice if you could open a new issue for the DLC request, so it won't get lost.
