### ISSUE TITLE
Add NUSspli to wiiu.hacks.guide's disc dumping instructions

### ISSUE THREAD

**Issue by jesstelford** [V10lator/NUSspli#223]
I was previously using WUP Installer as [instructed by wiiu.hacks.guide](https://wiiu.hacks.guide/#/dump-games?id=instructions), and hadn't even heard of NUSspli until a random forum post mentioned it.

It simplifies the whole process, and with its updated functionality it's worth adding to the wiiu.hacks.guide docs I think!

**Comment by jesstelford** [comment]
I've proposed adding it here: 
https://github.com/hacks-guide/Guide-WiiU/pull/180

**Comment by V10lator** [comment]
Thanks for the heads up but closing this here as it's not really a bug on our end.

**Comment by V10lator** [comment]
You're btw welcome to join our Discord for further talk about this, I just fear there's nothing we can do to change the guide.

https://discord.gg/B8ZBd6mrnV
