### ISSUE TITLE
Is there a way to remove the downloads?

### ISSUE THREAD

**Issue by Zethet** [V10lator/NUSspli#226]
I downloaded a game on my usb but that consumed all my storage and I would like to know if it can be erased somehow, thanks

**Comment by V10lator** [comment]
There's an option to delete after install in NUSspli. Other that that you can use FTP to delete the folder [icode]storage_usb/install[/icode]. On Tiramisu use https://github.com/Laf111/WiiUFtpServer/releases , on Aroma use the build-in FTP plugin.

Note that this is a place for bug reports, so for further quoestions switch to GBATemp or Discord, please.
