### ISSUE TITLE
FSA cache not in sync with MCP FS access

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [V10lator/NUSspli#227]
Hey there,
Just want to suggest a pretty essential feature to add to NUSpli.
They are cases, where the download fails, intentionally or not, from NUSpli. However, in those cases, the downloaded parts of the game in question remain on whatever device you've set it to download.
The same goes if you manage to download a game completely, but then, fail to notice it doesn't have the place to install it… because it's taken by that same downloaded game on the same drive.
The issue with all that, is that if the drive is part of the Wii U added drives, the partitioning is proprietary and doesn't allow deleting the files in question, taking unused space on the drive.

**Comment by V10lator** [comment]
Keeping the downloads was a heavily requested feature and with removing it probably 80% of the userbase would cry why they can't continue interrupted downloads anymore.

> However, in those cases

...NUSspli will auto-continue the download 10 seconds later (except you disabled that in the settings but even then you can continue the download manually whenever you want). Is there some error with this?

> The same goes if you manage to download a game completely, but then, fail to notice it doesn't have the place to install it

A failed game install should be cleaned up already. In case you still have files left after such an operation tell us which fils exactly, please.

> because it's taken by that same downloaded game on the same drive.

NUSspli checks the free space for both, download and installation, before starting the download. So there should never ever be a situation where it tells you enough space is free before downloading but then fails while installing. In case this is wrong: Tell us how to recreate, please.

> doesn't allow deleting the files in question

Tiramisu: https://github.com/Laf111/WiiUFtpServer/releases
Aroma: Has an FTP server build in

**Comment by PoorPocketsMcNewHold** [comment]
> NUSspli checks the free space for both, download and installation, before starting the download. So there should never ever be a situation where it tells you enough space is free before downloading but then fails while installing. In case this is wrong: Tell us how to recreate, please.

Except when you download, and install the game on the same USB Wii-U formated drive. Thanks for the FTP server solution however.

For me, it was : 

# ~20GB left. 
## - Download [Sonic & All-Stars Racing Transformed](https://www.pcgamingwiki.com/wiki/Sonic_%26_All-Stars_Racing_Transformed)
####	- Estimated : ~5GB :heavy_check_mark:  
## - Download [Deus Ex: Human Revolution](https://www.pcgamingwiki.com/wiki/Deus_Ex:_Human_Revolution)
####	- Estimated : ~11GB :heavy_check_mark: 


# ~15GB left
## - Install Sonic & All-Stars Racing Transformed
####	- Estimated : ~15GB left > ~11GB to download :heavy_check_mark: 


# ~4GB left
## - Install Deus Ex: Human Revolution
####	- Estimated : 4GB left :x:

**Comment by V10lator** [comment]
So you installed one game, then tried to install the second and it did start the installation but then it failed? That's indeed a bug, just not sure how to fix this.

**Comment by PoorPocketsMcNewHold** [comment]
> So you installed one game, then tried to install the second and it did start the installation but then it failed? That's indeed a bug, just not sure how to fix this.

Exact, because now, the storage is missing the available space to install it *(which is taken up by the actually downloaded game in itself)*

**Comment by V10lator** [comment]
@PoorPocketsMcNewHold Could cou test if this fixes the issue, please?
https://github.com/V10lator/NUSspli/actions/runs/6206578421#artifacts

**Comment by V10lator** [comment]
Should be fixed with v1.139
