### ISSUE TITLE
NUSspli Update Error (1.17)

### ISSUE THREAD

**Issue by Carlitosnu** [V10lator/NUSspli#23]
Hi, i'm other time.
Can't update from 1.17 to 1.19 that say
> "Error creating tamporaly directory!"

I attach a capture :)
![WIIU](https://user-images.githubusercontent.com/25675386/115810718-0481fa80-a3b4-11eb-9cb0-dd0545ec27d4.jpg)

**Comment by V10lator** [comment]
This is known and worked on. Just one question: Are you using Aroma CFW?

**Comment by Carlitosnu** [comment]
No is Mocha CFW, opened with hbl channel on the WiiU Menu

**Comment by V10lator** [comment]
Did you make sure the SD card isn't write locked? If so try one of the ALPHA6 versions here, it should give a better error message: https://public.nbg01.v10lator.de/NUSspli/

**Comment by V10lator** [comment]
Should be fixed with 1.20.

**Comment by Carlitosnu** [comment]
Can't update from 1.20Alpha 4 to 1.20 stable
The SDCard isn't locked
