### ISSUE TITLE
I/O error but I’m on the internet and apps that require internet work fine

### ISSUE THREAD

**Issue by Alvinf739** [V10lator/NUSspli#230]
![image](https://github.com/V10lator/NUSspli/assets/141074880/5b8ad843-0c62-4255-9181-b7947afd11fc)
 No matter what I do this pops up I think I might have to uninstall NUSspli and reinstall it

**Comment by ItsOnlyHer** [comment]
I've been getting the same error as well, I tried uninstalling NUSspli and reinstalling it using the actual Aroma file, but it still doesn't work. I'm glad to see another person getting this error, because if there's anything I know, is that 99% of people are smarter than I am.

**Comment by Alvinf739** [comment]
I’m reinstalling it ilyk what happens

**Comment by Alvinf739** [comment]
It didn’t work

**Comment by ItsOnlyHer** [comment]
> It didn’t work

I figured. I had already tried it. I tried unplugging it, plugging it back in, and even re-checking my internet settings.
Maybe it's a server problem? I'm just speculating at this point.

**Comment by Alvinf739** [comment]
Yea we just gotta hope our lord and savior V10lator sees this

**Comment by ItsOnlyHer** [comment]
Hopefully, it's temporary so nothing major has to happen.


Hopefully.

**Comment by Mazzix8080** [comment]
Still broken

**Comment by wuddigama** [comment]
Still broken, for context I updated Aroma several hours ago (looks like before this ticket was created) and was able to do a download from NUSspli at that time, however I'm now also currently experiencing this issue. Tested wifi, restarted my console and the NUSspli app -- eventually I received "The download returned a result different to 200 (OK): 504" and it stopped retrying.

**Comment by ItsOnlyHer** [comment]
> Still broken, for context I updated Aroma several hours ago (looks like before this ticket was created) and was able to do a download from NUSspli at that time, however I'm now also currently experiencing this issue. Tested wifi, restarted my console and the NUSspli app -- eventually I received "The download returned a result different to 200 (OK): 504" and it stopped retrying.

I got that same error once, but I was there, so I didn't pay much attention to it and kept on retrying. I'm trying to figure out why this would happen.

**Comment by Mazzix8080** [comment]
Im able to install again

**Comment by V10lator** [comment]
Can't recreate this. So either servers are having issues in some area only or (more likely) this is a connection issue in your end.
Wii Us WiFi is pretty weak and NUSspli is doing a lot of I/O, so at best use a LAN adapter.

**Comment by ItsOnlyHer** [comment]
End Of Download Report:
I downloaded 16 items in total, 13 were games, like Splatoon, Wii Party U, Wii Fit U, PIKMIN 1, 2 & 3, and 3 were DLC for the Taiko games. These were 22.68 GB in total. After 7 hours of waiting (yes really), they all installed without any issue. I would count this issue as "Semi-Resolved" or a small hiccup of NUSspli. I'll write here in case anything happens again.
