### ISSUE TITLE
HBL version only shows a black screen even on 1.138

### ISSUE THREAD

**Issue by TheBeast94YT** [V10lator/NUSspli#234]
What the title says. Running NUSspli for me shows a black screen and the only way out of it is to hard restart. I have updated to 1.138 and have 01sigpatches.rpx in my tiramisu folder. Am I missing something else considering all the files were the same the last time I successfully used the program (aside from the update)?

**Comment by V10lator** [comment]
Is your Tiramisu up to date (redownload from tiramisu.foryour.cafe and put the files on the SD card, overwriting existing ones) ?

**Comment by TheBeast94YT** [comment]
After replacing those files, the problem is still there.

**Comment by V10lator** [comment]
Two things you could do to help debugging this:
1) Use the DEBUG version and NUSspli while running https://github.com/dimok789/loadiine_gx2/raw/master/udp_debug_reader/UdpDebugReader.exe on your PC. Copy&paste the log after it blackscreened.
2) Grab the storage_slc:/sys/logs folder (via FTP), zip and upload it here.

**Comment by V10lator** [comment]
Closing cause nobody seems to be able to recreate this and no more reply from the OP.
