### ISSUE TITLE
Can't update the Aroma version

### ISSUE THREAD

**Issue by V10lator** [V10lator/NUSspli#24]
This is caused by Aroma not allowing to remove/overwrite a running WUHB file. That means it can't be fixed in NUSspli but needs a change in Aroma CFW.

**Comment by E1ite007** [comment]
Neither the channel or HBL version allows to autoupdate.
It shows "Error opening file: /vol/external01/NUSspli_temp/NUSspli/

Also. If you succeed at updating on HBL, when trying to launch NUSspli, it will give error code: 160-2203.

**Comment by V10lator** [comment]
@E1ite007 Please note that the channel and HBL update functions have been fixed with 1.20. So you'll need to wait for 1.21 for it to work. For example 160-2203 means file corruption and a file corruption issue while unzipping has been fixed with 1.20 (1.20-ALPHA8 to be exact).

**Comment by V10lator** [comment]
An Aroma dev told me:

> I'll add a function to the RPXLoadingModule to unmount the current .wuhb so you can override it while running it

So this bug will get closed as soon as that's ready. :)

**Comment by V10lator** [comment]
Marked as invalid as this is an Aroma bug. Anyway, as told above Aroma devs are working on it.
