### ISSUE TITLE
The app (Channel) says (You need aroma or tiramisu or your not on the latest version)

### ISSUE THREAD

**Issue by MK-WE** [V10lator/NUSspli#243]
Me again, i tried the channel and im on the latest aroma build and it says You need aroma or tiramisu or your not on the latest version

**Comment by MK-WE** [comment]
Im sorry if this is a mess up on my end but im kinda stupid soo  idk it may be a issue

**Comment by V10lator** [comment]
Use the Aroma updater which is shipped with Aroma to, well, update Aroma.
