### ISSUE TITLE
[v1.20-ALPHA6] Rare random crashes

### ISSUE THREAD

**Issue by V10lator** [V10lator/NUSspli#25]
Seems we fixed almost all crashes (like described in #22). There's only one rare crash left which I fail to track down.

**Comment by V10lator** [comment]
Additional info: The I/O queue has been ported to Linux and examined with Valgind. It's not the cause of this. Would love to port and examine other codes, too, but am facing endinaness differences.

**Comment by Carlitosnu** [comment]
Crash on press the **HOME** button on the title donwload section
