### ISSUE TITLE
MAJOR BRICKING ISSUS

### ISSUE THREAD

**Issue by WiiUEnthusiast** [V10lator/NUSspli#251]
Hi V10lator,I Just Want To Say Thanks For Your Contribution In The Modding Community But I Found A Major Flaw In The Homebrew Appstore Version Of Nusspli LITE,Because The WUHB Version Of Nusspli Kept Dissapearing I Used Nusspli LITE And... Brick
But Thankfully It Was Just The System Messing With Me
So Yea. Hopefully You Can Fix It.
Good Luck And Happy Modding.

**Comment by Masamune3210** [comment]
I'm going to go with either your nand is going bad or something is corrupted. Afaik, there is no way that nuspli could cause a brick simply by trying to use it

**Comment by V10lator** [comment]
No idea what the OP wants to say.
