### ISSUE TITLE
[request] reduce the power of vibrating of wii remotes when updating is finished

### ISSUE THREAD

**Issue by BeefBaconBiscuit** [V10lator/NUSspli#252]
Title, i literally just updated it and I wanted to check the update log here, i had my wiimote on my desk when it vibrated and gave me a heart attack when updating was finished

**Comment by V10lator** [comment]
There is no such thing as power: Wii mote rumble is either on or off. See https://wut.devkitpro.org/group__padscore__wpad.html#ga37ef1a83b1ed66259d5bfa64edddf3a5
