### ISSUE TITLE
NUSspli DSI exception

### ISSUE THREAD

**Issue by ODA-AG** [V10lator/NUSspli#258]
I am running the latest version 1.141 and I get this error message when it loses connection to the servers:

An error has occurred. Press POWER for 4 seconds to shutdown.
Core2: DSI exception at 0x0F2DB738 (SRR)) | DAR: 0x00000001
Tag: 0x4F53436F6E747874 (expected 0x4F53436F6E747874)
SRR1: 0x0000D072 | DSISR: 0x40000000
SRR0: 0x0F2DB738 nusspli | nusspli+0x0
LR9: 0x0103C494 coreinit.rpl | __OSTestAssistReadPhysical32+0x6C
LR10: 0x01041D6C coreinit.rpl | OSCheckThreadStackUsage+0xB0

**Comment by V10lator** [comment]
What CFW are you using?

**Comment by V10lator** [comment]
Really can't do anything when you don't tell me what CFW we're talking about. Also would need to have the full stacktrace, yours seems to be cutted. At best take your phone and make a photo of that exception screen.

Lastly:  In case you're running Aroma: What modules and plugins are you using?

**Comment by V10lator** [comment]
Closing cause of no more reply.
