### ISSUE TITLE
Downloaded games not working per environment

### ISSUE THREAD

**Issue by Waddlez3121** [V10lator/NUSspli#262]
Hey there! ~~I really went and made an account for this?~~ I downloaded some games using the version of NUSspli for the Tiramisu environment. I switched to Aroma for some other Homebrew things, but Tiramisu is still installed. Now, however, when I attempt to open the games through Aroma, they fail and say that the NNID they were downloaded with doesn't exist on my console and it wants me to redownload them.

Is there anything I can do except redownload them through the Aroma version? Would that even work, or do I need to switch back to Tiramisu for those games?

**Comment by Masamune3210** [comment]
its nothing to do with environment specific installations or anything like that, you probably just don't have aroma set up correctly with regards to sigpatches

**Comment by Waddlez3121** [comment]
> its nothing to do with environment specific installations or anything like that, you probably just don't have aroma set up correctly with regards to sigpatches

Actually, it looks like it was moreso a save data issue, but I'll look into making sure I set those up right. Thanks!
