### ISSUE TITLE
Unknown libcurl error 43

### ISSUE THREAD

**Issue by BradOnMac** [V10lator/NUSspli#263]
I try to download games, but randomly I see either "Unknown libcurl error 43" that turns into "Network error" or just the network error. I want to download games but I don't want to add another hour because of this glitch.

**Comment by V10lator** [comment]
What NUSspli version?

**Comment by BradOnMac** [comment]
The newest one. It must have been having issues with pretendo and aroma because when I switched to tiramisu it works like a charm

**Comment by V10lator** [comment]
I know this is a big request but could you retest with https://github.com/V10lator/NUSspli/actions/runs/7340553690/artifacts/1136750660 while having https://github.com/dimok789/loadiine_gx2/raw/master/udp_debug_reader/UdpDebugReader.exe running on your PC? If both, the Wii U and the PC are on the same network (and no firewall on the PC is interferring) this should produce a log. So just let it run untill the error screen shows up, then copy said log for me to have a log.

**Comment by BradOnMac** [comment]
I’ll do it after all of the games I wanted to download earlier are done. Will take some time

**Comment by BradOnMac** [comment]
So it might have been because of a dog crate

**Comment by coollad34** [comment]
Anyone know how to fix the search screen? I can't press the back button to go back to the main menu.

**Comment by BradOnMac** [comment]
> Anyone know how to fix the search screen? I can't press the back button to go back to the main menu. Edit: I'm sorry for asking the same question twice but idk what to do. It just won't let me go back to the menu. I'm stuck in the search screen when i press the back button. It doesn't do anything. Edit again fixed by powering it off.

Dawg this is my chat not yours gtfo

**Comment by V10lator** [comment]
Closing cause of no more reply.

**Comment by David-Anima** [comment]
Hello, I also have this issue, I've been wondering why it happened, but I saw this and wanted to comment. I can do the thing you mentioned to do, just not right now, but the 1st link doesn't work.
