### ISSUE TITLE
instyalling to nand says sd is currupt 

### ISSUE THREAD

**Issue by ulao** [V10lator/NUSspli#265]
I tried installing nusspli with wup installer and it says the sd is corrupt ( gets about 75% done. But I'm not installing to an sd? Also I tried putting the installer on another ds.

**Comment by V10lator** [comment]
Multiple issues with your bug report:
1) I searched and searched the sourcecodes: There's nothing telling the SD is corrupt. The only strings with the word "corrupt" inside are these:
```
Files might be corrupt or bad storage medium.
Try redownloading files or reformat/replace target device
```
```
Possible USB failure. Check your drives power source.
Files might be corrupt
```
2) You probably corrupted the files by i.E. not unmounting the SD card correctly before pulling it from the PC.
3) This is NUSspli support, not WUP Installer support.

**Comment by ulao** [comment]
possible, I installed an older version of nuspli then when back and installed the latest. When running I get another error will make a new ticket on it.

**Comment by V10lator** [comment]
This is for bug reports, not for generic questions / support. For questions/support switch to either our Discord or GBATemp, please.
