### ISSUE TITLE
Crash while downloading JPN games

### ISSUE THREAD

**Issue by AnotherFr4n6028** [V10lator/NUSspli#27]
I found an issue with this software. When i try to download japanese games since i've got a region free wii u, my wii u crashes every time. For now i only tried with MOTHER 2. If you know how to solve this issue that would be great! Thanks a lot!

**Comment by V10lator** [comment]
Could you tell me a infected title ID?

**Comment by V10lator** [comment]
Possibly dublicate of #25 / #22.

**Comment by AnotherFr4n6028** [comment]
Duplicate 

> Could you tell me a infected title ID?

The title ID of the game is 0005000010133300
