### ISSUE TITLE
Feature Request: Add Title loading

### ISSUE THREAD

**Issue by sionisaac** [V10lator/NUSspli#270]
Would it be possible to include a title launcher? A bit like FBI on 3DS. For installed titles add the ability to launch said title.

**Comment by sionisaac** [comment]
Where is the title launcher? You closed this as completed!

**Comment by Masamune3210** [comment]
If I'm not mistaken, close as completed is the default action when closing an issue. It doesn't actually mean that its completed. I know its confusing, blame Github

**Comment by V10lator** [comment]
> Where is the title launcher?

https://github.com/V10lator/NUSspli/assets/1312422/a541fca8-e658-4383-86ab-fbf26ac6c474

![image](https://github.com/V10lator/NUSspli/assets/1312422/a9749f5a-417c-4e62-b03b-39f7f4b83a97)

**Comment by sionisaac** [comment]
If this works I'll use nuspli as a replacement for system menu.

**Comment by sionisaac** [comment]
Tried Lau hing multiple installed titles and it hangs on every one.
