### ISSUE TITLE
[Problem] WiiRemote inputs becomes erratic if Wii U GamePad is not connected

### ISSUE THREAD

**Issue by Cueropedo** [V10lator/NUSspli#275]
The Wii Remote inputs become repeated if the Wii U GamePad is not connected when using NUSSpli.
Example, you open the app without the GamePad, try to navegate in the menu, and the D-Pad input will be repeatedly done in a loop, if you press A, the console will register as you press A constantly, which makes the app imposible to use.

I'm using the Aroma WUHB version.

**Comment by V10lator** [comment]
This bug reports raised big waves through the team - at a time nobody had access to a Wii U.

Anyway, now that I finally had access I tied the following scenarios:

1. Turn on the Wii U
2. Disconnect the battery from the gamepad
3. Connect a Wiimote
4. Start NUSspli

Can't recreate with this setup through. So either I'm doing something wrong which wiuld need you to describe better how to receate, or you're using some 3rd party Wiimote which behaves differently than a original Nintendo one.

**Comment by V10lator** [comment]
Also this is just a shoot into the blue but test this one and report if it fixes your issue, please: https://github.com/V10lator/NUSspli/actions/runs/7928266142#artifacts

**Comment by Cueropedo** [comment]
> This bug reports raised big waves through the team - at a time nobody had access to a Wii U.
> 
> Anyway, now that I finally had access I tried the following scenario:
> 
> 1. Turn on the Wii U
> 2. Disconnect the battery from the gamepad
> 3. Connect a Wiimote
> 4. Start NUSspli
> 
> Can't recreate with this setup through. So either I'm doing something wrong which would need you to describe better how to receate, or you're using some 3rd party Wiimote which behaves differently than a original Nintendo one.

Wii Remote is an official RVL-003 one.
But, my GamePad is currently broken, and has no battery, the Wii U boots without it. 
I power it on using the Wii Remote, here is a video on how I exactly do it step by step (also, showing the bug in NUSSpli, the controller model, how I power up the Wii U, etc):


https://github.com/V10lator/NUSspli/assets/64707859/7a22ab39-81aa-4af5-aaa8-a8b84aee4dfe

1. I turn on the console by the Wii Remote power button. (GamePad has no battery at all, so it never turns on)
2. Once it finish booting, I open the NUSSpli WUHB.
3. I wait, and once it finishes loading, I just press a button in the Wii Remote and the bug appears, NUSSpli starts looping the inputs I give (I will of course not press A, I did that in another time and it was a mess, I almost lost some data by doing that).

Will try your new build and see how it goes.

**Comment by V10lator** [comment]
This starts to get weird as I still can't reproduce:

https://github.com/V10lator/NUSspli/assets/1312422/2233f1ea-820e-4bc2-bf3d-67dbee6569dd

Only difference is that your Wiimote is without Motion Plus while mine is with... Don't think this will make any difference but will try with a Wiimote without next days, too. Else I have no clue how to even start debugging this without sending you one test build after the other, telling you how to produce logs and inspecting these.

**Comment by Cueropedo** [comment]
...All right, I found the root of the problem. I disabled the DRC Spoofer plugin... and it worked like it's supposed to. I completely forgot about that plugin, but was the one causing the issues.

Nobody had this situation before I guess, but maybe this can be added to a FAQ just in case someone has this problem. I apologise if this case was a waste of time.
