### ISSUE TITLE
Can't install titles with download on usb (1.20 && 1.21)

### ISSUE THREAD

**Issue by Carlitosnu** [V10lator/NUSspli#28]
The problem is when finish the installation to usb the game to download is PokeTournament

And the error is:
> Installation failed. Possible USB Error

**Comment by Carlitosnu** [comment]
On any title says![IMG_20210425_154600.jpg](https://user-images.githubusercontent.com/25675386/116009136-72f5d100-a5dd-11eb-844e-0d0d41cb4c12.jpg)

**Comment by Carlitosnu** [comment]
On 1.21 no work's

**Comment by V10lator** [comment]
Please make sure your USB drive is connected with a Y-cable.

**Comment by Carlitosnu** [comment]
> Please make sure your USB drive is connected with a Y-cable.

Yep the HDD is connected with a Y-Cable

**Comment by Carlitosnu** [comment]
Or with NUSspli downloaded game say a error![IMG_20210427_145556.jpg](https://user-images.githubusercontent.com/25675386/116304925-b2045d80-a768-11eb-8e07-c6c2a6b5ef5f.jpg)

**Comment by V10lator** [comment]
It still sounds like a issue with the USB drive. Tr connecting the Y-cable to a powefull wall charger or, even better, try a USB stick (but do this for testing only, not for regular gaming).

Also please don't track different bugs in the same report. This one is about "possible USB error", not "DLC/E-shop require Sig Patch", right?

**Comment by homebrewGT** [comment]
Try with 1.18 in the same Wii U and see if it installs...

**Comment by V10lator** [comment]
@Carlitosnu Could you please add the requested infos? Also after testing 1.18: What's the last version that works?

Also you told on Discord that the "DLC/E-shop require Sig Patch" screen is from Aroma CFW. Aroma CFW does not contain sigpatches so this is no bug. Will hide that part of you report now.

Lastly: Is anyone else able to recreate this (possible USB error) bug?

**Comment by V10lator** [comment]
Setting this to invalid untill the open questions have been answered.

**Comment by Carlitosnu** [comment]
Answered on discord server

**Comment by Carlitosnu** [comment]
All is solved
