### ISSUE TITLE
Nuspli unsupported Enviroment (Everything updated to latest version already)

### ISSUE THREAD

**Issue by willetsm** [V10lator/NUSspli#282]
![IMG_9357](https://github.com/V10lator/NUSspli/assets/161002598/52d77c19-7a54-4643-90dd-c197dea7b956)

**Comment by V10lator** [comment]
Your RPXLoader (part of Aroma) is unable to give the path of the currently running .wuhb file. This had been added to Aroma Beta 11 while Aroma is currently at Beta 16.

So your Aroma version is pretty out of date (more than a year!), update it ASAP!
