### ISSUE TITLE
FEATURE REQUEST: LAN/NAS (SMB / NFS) support for sources

### ISSUE THREAD

**Issue by HVR88** [V10lator/NUSspli#283]
I've searched a few different ways to see if this has already been requested but came up empty.

I'd love support to provide a LAN path to NAS via SMB, NFS, etc. to a collection of of files that have already been previously downloaded from Nin's servers (with *everyone knows the tools*)

I've got everything stored away and the ability to point NUSspli directly at those sources is much more convenient than having to move files on SD card and of course much faster than downloading all over again.

**Comment by V10lator** [comment]
MCP (Nintendo software) needs to be able to read the files you want to install. So this would need support from the (custom) firmware.
