### ISSUE TITLE
I/O Error on nusspli wii u aroma 

### ISSUE THREAD

**Issue by malik05051** [V10lator/NUSspli#284]
I got this error idk why
Plugins enabled :
Rverse

Using nintendo network idk why this occurs internet is enabled maybe server down i think ?

**Comment by V10lator** [comment]
Could you show a picture of the error screen (taken with the camera of your mobile phone, for example), please?

**Comment by Qonstrukt** [comment]
I'm also receiving an error on startup:
```
Network error:
  I/O error
```

I have not network issues with other apps like the web browser. Maybe the Nintendo store is just offline?

**Comment by V10lator** [comment]
Thanks, for some yet unknown reason PHP on NUSsplis API server wasn't running.
