### ISSUE TITLE
Everytime i try to add the nuspli folder on my sd card it will erase the files in the folder when i try to put it back in the Wii U 

### ISSUE THREAD

**Issue by KYVONxp3** [V10lator/NUSspli#287]
Everytime i try to add the nuspli folder on my sd card it will erase the files in the folder when i try to put it back in the Wii U What do I do

**Comment by Masamune3210** [comment]
check your sd card for damage, either to the filesystem or to the flash itself. sounds awfully close to what would happen in those two situations

**Comment by V10lator** [comment]
Beside what Masaume3210 told also make sure to correctly unmount the card before removing it from the PC, cause this also sounds like the files/folders haven't been flushed before you removed the card. See https://support.microsoft.com/en-us/windows/safely-remove-hardware-in-windows-1ee6677d-4e6c-4359-efca-fd44b9cec369 for more informations.
