### ISSUE TITLE
Channel version broken on Aroma (RPXLoader_GetPathOfRunningExecutable() failing)

### ISSUE THREAD

**Issue by greenkidneybean** [V10lator/NUSspli#294]
NUSspli not working in Aroma but .  Running NUSspli v1.147 on Aroma Beta 16 raises the error:

Unsupported environment.
Either you're not using Tiramisu/Aroma or your Tiramisu version is out of date.
RPXLoader error: RPX_LOADER_RESULT_NOT_AVAILABLE

Some context - I bought a used 32 GB Wii U, deleted all content/settings, installed Aroma and NUSspli channel and got error.  I then tried installing Tiramisu v0.1.2 and the NUSspli.rpx and it works fine in that environment but I still get this same error in Aroma.  

Vomiting some more details and speculation - I'd prefer not to have to switch environments to use NUSspli (my default is Aroma, and I'm also having issues using the Health & Safety inject to get to the environment loader).  I'm not sure if this Wii U was previously modded.  I have NUSspli working on an older 8 GB Wii U.

Cheers!

**Comment by V10lator** [comment]
Update Aroma (download from https://aroma.foryour.cafe and unzip on your SD card overwriting existing files).

Also might be a good idea to use the Aroma version on Aroma.

**Comment by greenkidneybean** [comment]
Thanks for your suggestion @V10lator!  I downloaded the [latest version of aroma](https://github.com/wiiu-env/Aroma/releases/tag/beta-16) and replaced the older files on my sd card but I'm still getting the same error.  I've also checked my Aroma Updater v0.2.2 and my Base-Aroma is up to date (2023-07-31).

I don't understand your suggestion to use the Aroma version on Aroma, could you elaborate a bit more on this?

Again, thanks for your response.  I know it sucks having folks open issues and asking for your time but I appreciate it.

**Comment by greenkidneybean** [comment]
Sweet Jesús, I got a fix.  I think my mistake was installing the [NUSspli-1.147-Channel.zip](https://github.com/V10lator/NUSspli/releases/download/v1.147/NUSspli-1.147-Channel.zip) via WUP Installer GX2, the fix was deleting that and dropping the [NUSspli-1.147-Aroma.zip](https://github.com/V10lator/NUSspli/releases/download/v1.147/NUSspli-1.147-Aroma.zip) into SD:/wiiu/apps/

Thanks again for your suggestion @V10lator

**Comment by V10lator** [comment]
Fixed with 1.148.
