### ISSUE TITLE
APD not correclty re-enabled in all cases

### ISSUE THREAD

**Issue by hugococa2004** [V10lator/NUSspli#300]
please create an option to shutdown the console after downloading a title or completing the download list

**Comment by V10lator** [comment]
I just looked at the codes and APD (automatic power down) gets re-enabled after the queue finished but before the green queue finished screen. So it should only prevent APD in case of an error (red error screen). IIRC it had been done this way years ago so people won't overlook the error screens.

Is it not working like that for you? So at what screen exactly doesn't it shutdown for you and are you sure automatic power down / energy saving is enabled in the Wii Us system settings?

**Comment by V10lator** [comment]
With the installer and downloader you're right through: It re-enables APD too late. Will be fixed with the next version but yea, from looking at the codes it should shutdown when using the queue, so is that broken for you?

**Comment by V10lator** [comment]
The milestone for 1.150 is there for a reason, so don't close as not planned, please. :)

**Comment by V10lator** [comment]
Fixed with v1.150.
