### ISSUE TITLE
[v1.149] libcurl error 43 (bad argument) combined with random freezes

### ISSUE THREAD

**Issue by ranvirsi1** [V10lator/NUSspli#302]
it does it for anything i try to download idk why

**Comment by V10lator** [comment]
Could you show a picture of that error screen, please?

**Comment by ranvirsi1** [comment]
Sure ![image](https://github.com/V10lator/NUSspli/assets/100595269/f16fe2cb-31e6-481e-b0cf-ec68811036bd)
Then the Wii U just freezes up and I have to unplug it

**Comment by ranvirsi1** [comment]
Oh and if a game/app does install it does this ![image](https://github.com/V10lator/NUSspli/assets/100595269/ab340220-0ca7-410a-a87d-0ab4457ce9cb)

**Comment by MrRubberDucky** [comment]
> Oh and if a game/app does install it does this ![image](https://private-user-images.githubusercontent.com/100595269/322221213-ab340220-0ca7-410a-a87d-0ab4457ce9cb.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMzMxNzYsIm5iZiI6MTcxMzAzMjg3NiwicGF0aCI6Ii8xMDA1OTUyNjkvMzIyMjIxMjEzLWFiMzQwMjIwLTBjYTctNDEwYS1hODdkLTBhYjQ0NTdjZTljYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTNUMTgyNzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDM2ODY5YWFmN2E1MTBlMGQ2NzRiNGRiMmYwZGUyYjI5NjJkYzZlOWE5ZmFlNDRiMmE2YWQ0NWU4M2ZlM2QwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZZCKEAtP3ZmCVITUPlh8PXL_VGNJEpMy-EkD1hUqlpY)

look into signature patcher module for aroma, it will solve this for you.

**Comment by Monadoblade618** [comment]
Having same issue with the librecurl maybe it's something on there side?

**Comment by ranvirsi1** [comment]
> > Oh and if a game/app does install it does this <snip>
> 
> 
> 
> look into signature patcher module for aroma, it will solve this for you. (nnid removed error that is)

Where can I get that?

**Comment by MrRubberDucky** [comment]
> > > Oh and if a game/app does install it does this
> > 
> > 
> > look into signature patcher module for aroma, it will solve this for you. (nnid removed error that is)
> 
> Where can I get that?

Sorry, I should've linked that but you can get it from this repository -> https://github.com/marco-calautti/SigpatchesModuleWiiU/releases/

iirc you put it in `wiiu/environemnts/aroma/modules` (same should also work for tiramisu env)

**Comment by V10lator** [comment]
Stay on topic, please, or I'll have to clean up. For generic questions, like sigpatches, we have FAQs, GitHub and Discord support chats.

**Comment by V10lator** [comment]
As a first debugging step could one of the affected users run a DEBUG build of NUSspli, please? At the same time run https://github.com/dimok789/loadiine_gx2/raw/master/udp_debug_reader/UdpDebugReader.exe on your computer (make sure no firewalls or stuff are blocking connections between your Wii U and your PC).

This should produce a log output at UdpDebugReader while NUSspli is doing various things. With this setup running recreate the issue and just take a screenshot of the UdpDebugReader window once you see the red error screen on your Wii U then upload this screenshot here, please.

Thanks in advance to whoever will help in debugging. :)

**Comment by V10lator** [comment]
Also everyone affected tell me if you're using Aroma or Tiramisu, please, and if Aroma if you're using the Aroma or Channel version of NUSspli.

**Comment by ranvirsi1** [comment]
Sure.                                                                                                                                                                                                                                                                       I will run the debugger if i can

**Comment by ranvirsi1** [comment]
> Also everyone affected tell me if you're using Aroma or Tiramisu, please, and if Aroma if you're using the Aroma or Channel version of NUSspli.

I'm using aroma and the aroma version of NUSspill

**Comment by ranvirsi1** [comment]
@V10lator is there a Mac version of udp debug reader as I don't have a windows machine 🥲

**Comment by V10lator** [comment]
@ranvirsi1 There's udplogreader. This is part of the homebrew SDK, so more complicated to install through. You would basically follow this: https://devkitpro.org/wiki/Getting_Started#macOS - then use pacman to install wut-tools. Or you somehow compile this for yourself: https://github.com/devkitPro/wut-tools/tree/master/src/udplogserver .

Sorry that I can't be of more help but am on Linux, not experienced with Mac.

udplogreader is just a CLI tool through, so you start it from terminal and you won't get any output except when the Wii U wants to log something.
You should already see Aroma logging some things while the Wii U boots through, like this:
![image](https://github.com/V10lator/NUSspli/assets/1312422/b00c16b7-ad5f-4067-9d27-01f6d72bb6e8)

**Comment by AorsiniYT** [comment]
> Also everyone affected tell me if you're using Aroma or Tiramisu, please, and if Aroma if you're using the Aroma or Channel version of NUSspli.

The problem occurs in both the aroma and the channel version, I have already tried both versions, I also tried the tiramisu and it is the same.

**Comment by AorsiniYT** [comment]
![image](https://github.com/V10lator/NUSspli/assets/34718505/2c4250c0-1634-4e38-96e7-6c0668ec0228)
It stops there and the console stops completely, I have to turn it off and on again from the console

**Comment by V10lator** [comment]
@AorsiniYT Do you remember what the screen showed when it froze? Cause this doesn't look like it even reached the red error screen to me. Also could you maybe try to download the `storage_slc:/sys/logs` folder with FTP, zip it and handle it to me, please? Maybe this shows why it crashed for you.

**Comment by Kadrevex** [comment]
Just a quick note, not sure if this is related at all. I've been having the libcurl 43 error for a few weeks and could only download small games. Last night I reset my router and downloaded games that are a few gigs with no problem at all .
   After downloading for most of the day with no problems, I got a libcurl error and then kept getting them again like before.
  I reset my router and now I can download big files again.

**Comment by ranvirsi1** [comment]
> Stay on topic, please, or I'll have to clean up. For generic questions, like sigpatches, we have FAQs, GitHub and Discord support chats.

So um where can i find the faq and discord?

**Comment by Kadrevex** [comment]
> So resetting a router is the fix?

Not a fix, but seems to help.

**Comment by ranvirsi1** [comment]
> > > > Oh and if a game/app does install it does this
> 
> > > 
> 
> > > 
> 
> > > look into signature patcher module for aroma, it will solve this for you. (nnid removed error that is)
> 
> > 
> 
> > Where can I get that?
> 
> 
> 
> Sorry, I should've linked that but you can get it from this repository -> https://github.com/marco-calautti/SigpatchesModuleWiiU/releases/
> 
> 
> 
> iirc you put it in `wiiu/environemnts/aroma/modules` (same should also work for tiramisu env)

Dosent seem to do anything it still won't let me launch the game I used

**Comment by V10lator** [comment]
Told you to stay on topic or I'll have to clean up so here we go...

> So um where can i find the faq and discord?

https://gbatemp.net/threads/nusspli-install-content-directly-from-the-nintendo-update-servers-to-your-wii-u.566055/
https://discord.gg/B8ZBd6mrnV


To the rest: Am still waiting for a debug log of the red error screen as the log from @AorsiniYT is from a crash before that screen.

**Comment by johnblade** [comment]
Updated last week to aroma, and had an update today for envloader and aroma base.
Previously I used tiramisu with nuspli 0.145 and never add this issue.
I will test on ethernet later. Don't hesitate to tell me if I can help by sending debug logs or other things.

**Comment by V10lator** [comment]
Do not just switch to LAN adapters, send logs as requested:

> As a first debugging step could one of the affected users run a DEBUG build of NUSspli, please? At the same time run https://github.com/dimok789/loadiine_gx2/raw/master/udp_debug_reader/UdpDebugReader.exe on your computer (make sure no firewalls or stuff are blocking connections between your Wii U and your PC).
> 
> This should produce a log output at UdpDebugReader while NUSspli is doing various things. With this setup running recreate the issue and just take a screenshot of the UdpDebugReader window once you see the red error screen on your Wii U then upload this screenshot here, please.
> 
> Thanks in advance to whoever will help in debugging. :)

**Comment by andrew-stclair** [comment]
I downloaded the debug version and ran the UdpDebugReader while downloading stuff.

![Screenshot 2024-05-11 195014](https://github.com/V10lator/NUSspli/assets/4944499/3fa9a732-733e-4431-ab5f-0e91a343d8db)

**Comment by V10lator** [comment]
@andrew-stclair And it crashed before the red error screen? Something is going weird here...

**Comment by V10lator** [comment]
@andrew-stclair or someone other affected: Could you retry grabbing a debug log with this version, please? https://github.com/V10lator/NUSspli/actions/runs/9043164439 (that's basically NUSspli nightly and you normally should not use this but it might help with the crashes, letting the log flow a bit more. It might means no guarantee through, I'm just shooting into the blue to see what happens here).

**Comment by andrew-stclair** [comment]
Same result unfortunately. Wii U red screens with the same error and the last line in the log output is `Download thread spawned!`

then no new lines are printed

**Comment by V10lator** [comment]
Okay, so a new guess: There's a network (WiFi) error which causes the red screen while at the same time disconnecting the log connection. So we can't see what gets logged after that connection error.

Now this ofc. makes debugging way more complicated.

@andrew-stclair Did it crash through or was it possible to continue the download with the test version?

**Comment by V10lator** [comment]
After a lot of code reviewing and documentation reading it looks like error 43 is not our bug!

It is CafeOS returning "Non-supported option" to some WUT call (maybe socklasterror? But that's really something for WUT devs to figure out, just can't pass the information forward as I'm banned there).

That also means it's no libCURL error: LibCURL does the completely right thing here as the errno WUT passed to libCURL is a invalid argument in that case.

So just the crashes left...

**Comment by andrew-stclair** [comment]
I'll run through a game download completely after work and see if i get any crashes. But when i was testing for you on the nightly builds i was not getting any.

**Comment by V10lator** [comment]
Hopefully fixed with v1.150.

**Comment by andrew-stclair** [comment]
To add to this, i got a USB Serial Debugger going using the [plugin from Aroma for it](https://github.com/wiiu-env/USBSerialLogger).

```
00;32;48;717: Mon 20 May 2024 19:06:08.105      Calling curl_easy_perform()
00;32;48;718: Mon 20 May 2024 19:06:08.107      Download thread spawned!
00:37:56:309: NET: >>> Received request to kill all sockets.
00:37:56:311: NET: Socket binding (resource: 0x00001a82)
00;37;56;192: *** INFO: Thread:0x1174d540 Stack Size:0x0000fff8 Stack Used:0x000019e0 Name:NUSspli downloader
00;37;56;195: Mon 20 May 2024 19:11:15.584      STACK: NUSspli downloader: 0x000019E0/0x0000FFF8
00;37;56;195: Mon 20 May 2024 19:11:15.585      curl_easy_perform() returned: 43
00;37;56;196: Mon 20 May 2024 19:11:15.585      curl_easy_perform returned an error:  (43/0)
File: /vol/storage_usb01/install/game/0000000c.app
00:38:00:345: NET: Change admin state (1 -> 1)(iface:0 link:2)
00:38:00:345: [WD]>>>> Linkup msg from Net
00:38:00:355: wlc_mlme_join_cmd called with Command 0x3 Length 0x21
00:38:00:359: NET: Change admin state (2 -> 2)(iface:1 link:2)
00:38:00:359: NET: Change admin state (1 -> 1)(iface:0 link:3)
00:38:00:466: [WD]>>>> Linkup msg from Net
00:38:00:475: wlc_mlme_join_cmd called with Command 0x3 Length 0x21
00;38;05;371: Mon 20 May 2024 19:11:24.760      Resetting network!
00:38:08:457: Acquired IP address via DHCP client for interface: wl0
```

Don't know if anything in there is of assistance

**Comment by sebastian2008JFG** [comment]
Gente ayuda todavía me aparece este mismo error en la última versión de Nusspli y no puedo descargar mis juegos

**Comment by sebastian2008JFG** [comment]
Network error: Internal WUT error

See https://github.com/V10lator/NUSspli/issues/302#issuecomment-2108134284 Next attempt in 1 seconds.

NUSspli v1.151

**Comment by sebastian2008JFG** [comment]
Arreglen por favor la gente de Nusspli ese error

**Comment by V10lator** [comment]
English, please, else I have no idea what you're saying.

**Comment by V10lator** [comment]
> Network error: Internal WUT error

It says internat WUT error for a reason: Not our bug but from DevktiPro / WUT.

**Comment by kaiopiola** [comment]
closed but it keeps happening
