### ISSUE TITLE
Libcurl error 

### ISSUE THREAD

**Issue by Monadoblade618** [V10lator/NUSspli#303]
I get this error every 10 seconds and after awhile just freezes my whole Wii u making big downloads practically impossible 
![2024-04-13-10-42-52-878](https://github.com/V10lator/NUSspli/assets/166937068/11204190-de29-4b36-834c-c920b1d82314)

**Comment by MrRubberDucky** [comment]
Wi-Fi downloading on Wii U is pretty bad, if you're not using a ethernet adapter of some sorts then it's what happens.

**Comment by Monadoblade618** [comment]
It worked fine a few months ago left it on when I went to work and came back to the games installed

**Comment by MrRubberDucky** [comment]
> It worked fine a few months ago left it on when I went to work and came back to the games installed

Ah ignore my message then, my exposure to this is pretty limited. Apologizes for cluttering up your issue! (only started using it this month)

Though now that you say, I suppose I had a similar experience under Wi-Fi as of late which is main reason why I just got an ethernet adapter. It would constantly throw up libcurl errors either instantly and get forever stuck - or in some cases freeze up the entire console - or it would do it constantly after every minute-two or so of downloading (speeds randomly going to 0Mb/s followed by libcurl error 5 seconds later)

Maybe NUSpli has some issue with handling active Wi-Fi connection? 🤔

**Comment by ranvirsi1** [comment]
I'm having the exact same issue and it depends for small downloads it works like a charm but if I'm downloading like splatoon it will just freeze up

**Comment by ranvirsi1** [comment]
And yeah and it sometimes says 99 days left for Downloading the content

**Comment by V10lator** [comment]
Ofc. this cryptic error message and freezes are a bug. Anyway, this bug report is a duplicate, so move over to #302 , please. Also this will need one of you who can recreate this to help me debugging. Will write more details about that at #302 later.
