### ISSUE TITLE
Nusspli issue

### ISSUE THREAD

**Issue by ZedG95** [V10lator/NUSspli#310]
I installed and ran Nusspli on my Wii U and went to download a game.  The game download completed but when I went to run the game, it said I needed to buy the game as the user was deleted.  Needs fixed as I believe the key gen doesn't work.  Not sure if it is due to only running Aroma tho.

**Comment by Masamune3210** [comment]
Not a NUSspli issue, you are lacking sigpatches which are needed to play anything without a valid signature.

**Comment by ZedG95** [comment]
I wish that piece of info was part of the readme.  But I've gotten it all figured out.

**Comment by HathewayWill** [comment]
> Not a NUSspli issue, you are lacking sigpatches which are needed to play anything without a valid signature.

is there a guide for this?

**Comment by HathewayWill** [comment]
> > Not a NUSspli issue, you are lacking sigpatches which are needed to play anything without a valid signature.
> 
> is there a guide for this?

https://www.reddit.com/r/wiiu/comments/1eo72ie/cant_install_software_because_i_need_sig_patch/

for anyone in the future looking for this
