### ISSUE TITLE
Problem with downloaded games - Nintendo Network Id not compatible

### ISSUE THREAD

**Issue by Gumaji08** [V10lator/NUSspli#311]
Hey! I installed Aroma on my Wii U recently following the instructions from wiiu.hacks.guide and everything worked great. I also installed NUSspli using the V10lator instructions from here on Github: I downloaded the Aroma version and added the NUSspli.wuhb file to the 'apps' folder on my SD card. On the Wii U menu, the NUSspli icon popped up, so I opened it... Just for a little test, I tried downloading a small game: Dr. Mario, the download worked and the game icon was in the menu as well. But every time I try to launch the game (and others), an error message pops up: "Can't use this software. The Nintendo Network ID used to purchase this software has been deleted. I tried to search for a possible solution but found almost nothing related to this error specifically, would it have something related to 'sigpatches'? If does, what could be the better solution?

I'm using Aroma and NUSspli already being logged in with my Nintendo Network ID, so I tried using a new user who doesn't have NNID but the error persisted.

**Comment by Masamune3210** [comment]
Aroma doesnt come with sigpatches. Go get them.
