### ISSUE TITLE
Crash when trying to download via USB

### ISSUE THREAD

**Issue by SninkAran** [V10lator/NUSspli#32]
I have tried downloading games directly to USB, because my SD is low capacity, and whenever I try, it gets stuck, it doesn't even let me exit the application, so I have to force shutdown

The games tested were:
LEGO Batman 2 reached 1%
The Amazing Spider-Man reached 44%

USB:
Kingston DataTraveler 100 G3 32gb
I formatted it multiple times and it still kept giving me the error

Help please, I realy want to download games directly to the USB 😥

**Comment by V10lator** [comment]
Please don't try to download to flash media. Download to a USB HDD with a Y-cable instead.

**Comment by V10lator** [comment]
Also please try:

- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.29-ALPHA1-Aroma-DEBUG.zip
- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.29-ALPHA1-Channel-DEBUG.zip
- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.29-ALPHA1-HBL-DEBUG.zip

**Comment by SninkAran** [comment]
> Please don't try to download to flash media. Download to a USB HDD with a Y-cable instead.

So there is no way that at least in the future it will be possible to download it directly to the USB Flash drive?

**Comment by V10lator** [comment]
It isn't recommended to use flash drives at all: https://en-americas-support.nintendo.com/app/answers/detail/a_id/1474#s1q8 - I don't say it can't work, just that Nintendo doesn't suppot it so the fist check to do is to try to download to a harddrive. If i works with a harddive it's the fault of the flash drive, simple as that.

On a site node: Dif you try the alpha version yet?

**Comment by SninkAran** [comment]
well, I haven't tried the Alpha yet, I'll try it in a while

But on the other hand I tried to download lighter games on the USB Flash memory, in this case a Kirby game from NES, and it did download and install it perfectly

I don't know if that changes something, but I'm telling you anyway

**Comment by SninkAran** [comment]
Well bud thank you so much, I already checked, and yes the problem was that I was using a flash drive, I already switched to an HDD and the game downloaded correctly 
On a Side Note: what's new in the Alpha?
