### ISSUE TITLE
I have a dump of my game that isn't on Nusspli

### ISSUE THREAD

**Issue by Santabo** [V10lator/NUSspli#326]
I got a game called Skylanders Imaginators for my birthday once and the game doesn't appear to be in Nusspli's database but I only have the European (PAL) version, how am I meant to contact to send the dump, V10lator?

Most of the other Skylanders Games for Wii U are there but not Imaginators.

**Comment by V10lator** [comment]
Hi and thanks for the offer to send the dump.

Sadly we don't host any warez through for legal reasons. NUSspli downloads from Nintendo own servers instead (so the one distributing the Wii U Software packages is Nintendo itself, not us).

Some games, like skyland imaginators, where not releases on the eshop but as discs only. These games are not on Nintendos servers so NUSspli can't download them for the reason above.

We also won't add links to 3rd party servers to NUSspli cause the content could change at any time (to maleware, for example). All disc only releases have been preserved by others to multiple sites (like the web archive) through and it's simple to google for them.
