### ISSUE TITLE
"The Nintendo network ID used to purchase this software has been deleted."

### ISSUE THREAD

**Issue by yeeeeeeeehaaaaaw** [V10lator/NUSspli#329]
When I try to open a game that I downloaded from NUSspli, it says "This software cannot be used. The Nintendo Network ID used to purchase the software has been deleted. You need to purchase this software from the Nintendo eShop again to be able to use it. Go to Nintendo eShop?" And when I go to the eShop, obviously, it won't let me download it. Is there a fix to this/a reason this is happening?

**Comment by Masamune3210** [comment]
sigpatches. get them

**Comment by yeeeeeeeehaaaaaw** [comment]
> sigpatches. get them

what's a sigpatch? also thanks for helping

**Comment by Masamune3210** [comment]
google
