### ISSUE TITLE
Search in title list freezes console

### ISSUE THREAD

**Issue by eku** [V10lator/NUSspli#33]
I'm on NUSspli 1.28 (HBL version). When pressing 'Y' to search in the title list the console freezes. Only power off is possible.

**Comment by V10lator** [comment]
What's you consoles region and language?

**Comment by eku** [comment]
My console's region is EU/PAL and language is German.

**Comment by V10lator** [comment]
So same as mine which means we can rule this out. Anyway, please try one of these:

- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.29-ALPHA1-Aroma-DEBUG.zip
- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.29-ALPHA1-Channel-DEBUG.zip
- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.29-ALPHA1-HBL-DEBUG.zip

**Comment by eku** [comment]
This one works, i.e. it displays the keyboard and applies the filter to the title list.  I don't see any commits since 1.28 and wonder what the difference is from 1.29ALPHA1.
