### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by 5ant1a6o** [V10lator/NUSspli#34]
once I lauch NUSspli it shows a red screen showing this message:

curl_easy_perform returned a non-valid value: 52

--->network error
failed while trying to download data, probably your router was turned off,
check the internet connection and try again.

I checked all that and made sure the wiiu is connected to the internet, by browsing on the explored of the console but still I get this red screen.

help me please.

**Comment by V10lator** [comment]
Do older versions work and if so what's the first one broken?

**Comment by V10lator** [comment]
No more reply since 1+ week. Also different, unclear statements on Discord. So closing this as invalid as we're not even sure you're using the newest NUSspli version.

**Comment by V10lator** [comment]
Feel free to reopen after giving the requested informations though. Requested informations are:

- Do older versions work and if so what's the first one broken?
- Does 1.31 work?
- What's the exact version you're using?
