### ISSUE TITLE
NUSspli says that there isn't enough space in the MLC even tho i'm pretty sure i do have enough

### ISSUE THREAD

**Issue by DARKLOL680** [V10lator/NUSspli#350]
hello, i tried downloading a game with NUSspli but it says that there isn't enough space in the MLC even tho i'm pretty sure i do have enough space both in the NAND (30gb) and the sd card (64gb)

it only happens with games that weigh more than 10gb since i could download other games
the game i tried to download are Zelda BOTW and Donkey Kong: Country tropical freeze

and what even is MLC ?

Edit: it only happens if i says yes to download the updates, which i did

**Comment by V10lator** [comment]
No Wii Us with 30 GB of free NAND/MLC exist, the max is 25 GB: https://www.nintendo.com/en-gb/Support/Wii-U/Storage/How-much-internal-storage-space-is-available-for-saving-data-/How-much-internal-storage-space-is-available-for-saving-data-678131.html

Most likely you have some things installed already, so it's less, see https://en-americas-support.nintendo.com/app/answers/detail/a_id/1516/~/how-to-determine-available-storage-space-on-a-wii-u-console

BOTW is roughly 10 GB and the update is roughly 3 GB. So when you download to NAND and install to USB (or vice-versa) this will need 13 GB. If you download and install to NAND this doubles to 26 GB through.

So NUSspli ist completely right. Downloading to USB or SD and installing to NAND should work just find.
