### ISSUE TITLE
NUSspli is stuck on the Goodbye ! screen

### ISSUE THREAD

**Issue by DARKLOL680** [V10lator/NUSspli#351]
when i opened NUSspli it told me that the verification failed and i should check in the settings or something and when i tried to close the app it said it is gonna take some time but it has been stuck for an hour now

and when i shut down my console and restart it it just brings me to the Goobye ! screen again

**Comment by DARKLOL680** [comment]
ok, it just took a REALLY long time

**Comment by DARKLOL680** [comment]
it's not solved tho, the message says

SSL error:
    Verification failed
check your Wii Us date and time settings


it didn't happens before and i checked the date and time settings and nothing changed, i really don't know what happened

also the screen is red

**Comment by V10lator** [comment]
Duplication of #320
