### ISSUE TITLE
WiiU with tiramisu, NUSspli i/o error. 1.153 version

### ISSUE THREAD

**Issue by GrisNeutro** [V10lator/NUSspli#353]
Everything was working fine till today, trying to download and a red screen with an i/o error is coming up... are the servers working??? thanks in advance...  i made a new fresh install and still happening... game list comes up, but when i try to download a game, red screen with an i/o error comes up. "check the network settings" 1.153 ver. Internet is working fine, restored network settings and everything is fine except of this. Cant download anything from the store.

**Comment by Theonlygabry** [comment]
Same problem here too!

**Comment by Theonlygabry** [comment]
Actually, trying to download from WiiUDownloader doesn't work too, so the servers might be down.

**Comment by GrisNeutro** [comment]
> Same problem here too!

when did that happened to you??? everything was ok till today

**Comment by GrisNeutro** [comment]
Is Nintendo blocking it???

**Comment by Theonlygabry** [comment]
![image](https://github.com/user-attachments/assets/1c489206-b471-4c4f-bd02-700b700e359b)

Tried to ping the nintendo servers that Nusspli uses, actually they seem to be down at the moment.

**Comment by GrisNeutro** [comment]
> ![image](https://private-user-images.githubusercontent.com/67585645/365804143-1c489206-b471-4c4f-bd02-700b700e359b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTQ3MDcsIm5iZiI6MTcyNTkxNDQwNywicGF0aCI6Ii82NzU4NTY0NS8zNjU4MDQxNDMtMWM0ODkyMDYtYjQ3MS00YzRmLWJkMDItNzAwYjcwMGUzNTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDIwNDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YjFlMmM3Y2VjM2FmYmMxMzJhOWQ2ZGI1NmQ4ZmIzNzM4ODFiMzA3NmMxOGQ0NTRmN2MzMWYyOTdlY2YzZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.32e0nRcRn5e_csHqnOHZ0x4gsxzpelSmi3g13DUWlLA)
> 
> Tried to ping the nintendo servers that Nusspli uses, actually they seem to be down at the moment.

Servers down??... i hope the issues will be solved. Good to hear thats not only my problem. Is there any other store to download from??

**Comment by GrisNeutro** [comment]
Everything is working fine now... i guess that sometimes servers are down cause lots of connections or maybe they reset them... if this happens to you just wait a couple of hours and try later.
