### ISSUE TITLE
Game goes to black screen

### ISSUE THREAD

**Issue by TOOPAKUE** [V10lator/NUSspli#355]
I have downloaded Rhythm Heaven Fever for Wii from Nusspli. When I downloaded it, it worked just fine, but after a while it started giving me a black screen either on boot or during loading screens. The only way for me to get out of the black screen is reboot the console. If I redownload the game, this issue is fixed, but only for a while. After a few hours, I start getting the exact problem again. It is very annoying and I'm not sure why this is happening.

**Comment by V10lator** [comment]
Sounds like a problem of your firmware or USB drive but not NUSspli related.

**Comment by TOOPAKUE** [comment]
What exactly does that mean and where could I find information about fixing it?
