### ISSUE TITLE
"Files might be corrupted" error message when trying to install from SD card?

### ISSUE THREAD

**Issue by aliceswii** [V10lator/NUSspli#356]
Hi! 
So I"m pretty much new to this whole home brewing thing. I've been downloading and installing games with NUSspli with no problems whatsoever for the past few days. However, when I try to install games that I downloaded to my computer and put in my SD card, it gives me an error message. I tried installing these games using WUP instead and it didn't give me an error but it just froze and stopped installing completely and I had to turn off the console to get out of there. 
What I find weird is that this only happens when I try installing from my SD card and not when I download directly from NUSspli. Does anyone have any suggestions?

**Comment by V10lator** [comment]
Does it work to install things downloaded through NUSspli directly?

**Comment by aliceswii** [comment]
Yes, it does, which is why I find it weird :(

**Comment by V10lator** [comment]
Okay, so NUSspli issue. Could have multiple reasons why the files are corrupted. The most likely one is removing the SD card from the PC without unmounting. I guess you use windows? If so have a look at this: https://support.microsoft.com/en-us/windows/safely-remove-hardware-in-windows-1ee6677d-4e6c-4359-efca-fd44b9cec369

For more questions hop to our discord or gbatemp, please.
