### ISSUE TITLE
Multipul errors….

### ISSUE THREAD

**Issue by mafolsson** [V10lator/NUSspli#357]
Hello!

I’ve tried to install multipla games through NUSplis and this error keep coming up after updating the app! Anyting you can do?

![IMG_4349](https://github.com/user-attachments/assets/559a4a0b-3495-4a1e-8ec9-7d423aafb48b)

**Comment by V10lator** [comment]
Duplication of #302

https://github.com/V10lator/NUSspli/issues/302#issuecomment-2108134284
> After a lot of code reviewing and documentation reading it looks like error 43 is not our bug!
> 
> It is CafeOS returning "Non-supported option (errno 92) to some WUT call (maybe socketlasterr? But that's really something for WUT devs to figure out, just can't pass the information forward as I'm banned there).
> 
> That also means it's no libCURL error: LibCURL does the completely right thing here as the errno WUT passed to libCURL is a invalid argument in that case.

https://github.com/V10lator/NUSspli/issues/302#issuecomment-2119917709
> 00:37:56:309: NET: >>> Received request to kill all sockets.
00:37:56:311: NET: Socket binding (resource: 0x00001a82)

> 0;37;56;195: Mon 20 May 2024 19:11:15.585      curl_easy_perform() returned: 43
