### ISSUE TITLE
Nusspli crashes when exiting

### ISSUE THREAD

**Issue by Nitro31LA** [V10lator/NUSspli#359]
Nusspli crashes when trying to exit, even without installing anything.

**Comment by V10lator** [comment]
What version and CFW?

**Comment by Nitro31LA** [comment]
Aroma CFW and version 1.153 aroma zip

**Comment by OriginalWooomy** [comment]
for me too, under the exacts same conditions; AROMA CFW and NUSSPLI updated to last release. I also don't have autoboot to aroma. I boot manually every time via info/security. I was erasing some of my games on my usb stick before entering nusspli

**Comment by V10lator** [comment]
So how do you define crashing? I.e. what's the last screen you see and is audio normal?

Also what Aroma plugins do you have?

**Comment by OriginalWooomy** [comment]
the last screen i saw is Goodbye !! with the first few notes looping (not normal audio). i have swip swap, ftpiiu, inkay, sdcafiine, homebrew on wii , DRC region free,Signature Patcher. It happened again today and i don't want it to corrupt my wiiu

**Comment by V10lator** [comment]
Closing cause of no more reply, so root of the issue remains unknown.
