### ISSUE TITLE
"There's a problem with the system memory" when launched NUSspil.

### ISSUE THREAD

**Issue by Hamoodynumber1** [V10lator/NUSspli#364]
I downloaded the standard Aroma package, moved the file to where it should be, and ran it from the HOME Menu only to be met with a System Memory error with the code 160-2203.
![IMG_2057](https://github.com/user-attachments/assets/eb548c6d-7de8-4252-b0a0-853e21550eb8)

I use an external storage to store my downloaded games.

Other than that. It appears my Wii U is largely unaffected as I can browse Miiverse. This issue only seems to happen anytime I launch NUSspil.

**Comment by V10lator** [comment]
Is Aroma and NUSspli latest version? If so I would think this is an Aroma bug but really unsure.

**Comment by V10lator** [comment]
Maybe crashlogs help, so grab them with https://hb-app.store/wiiu/WiiUCrashLogDumper , please.

**Comment by V10lator** [comment]
Closing this cause of no more reply, so assuming this was either a hardware or a CFW issue and NUSspli was just good at triggering it.
