### ISSUE TITLE
My Wii U doesn't want to launch the game

### ISSUE THREAD

**Issue by LaCabanedeLH** [V10lator/NUSspli#366]
I want to launch my game but my wii u says "The user that installed this app has been removed please buy it" I translated it but it's that. So do i need to install it in Wup installer?

**Comment by Masamune3210** [comment]
You are likely missing sigpatches. Go find them and install them.

**Comment by TTVMic8** [comment]
if your still looking for it, its this link: https://github.com/marco-calautti/SigpatchesModuleWiiU/releases
put the rpx file in sd:\wiiu\environments\aroma\modules\setup
_**IT IS NOT SUPPOSED TO BE PLACED IN sd:\wiiu\apps**_
once you do that it should work
