### ISSUE TITLE
NUSspli update server offline

### ISSUE THREAD

**Issue by Frenzybomb** [V10lator/NUSspli#367]
![IMG_1718](https://github.com/user-attachments/assets/d27e6c87-574d-45da-903c-91d80eaf716e)

So was just browsing in nusspli then I got this error is there a fix or not someone please help me

**Comment by juliobutinblender** [comment]
![17309448238067513526525182820803](https://github.com/user-attachments/assets/d720cf35-61c4-4a22-bdea-b98f028ce86b)
 Same here

**Comment by Frenzybomb** [comment]
Is there a fix

**Comment by Manu959595** [comment]
I had the same issue but idk what i pressed but it got fixed, i think it was B just for canceling that and it worked for me

**Comment by Manu959595** [comment]
https://github.com/user-attachments/assets/35eae535-5e10-469c-8a2b-0067104f79d3

**Comment by V10lator** [comment]
NUSspli update server has issues. No ETA. Just press (B) to skip the update check.

**Comment by V10lator** [comment]
Should be fixed now.
