### ISSUE TITLE
NUSspli games not loading. Nintendo ID game has been deleted.

### ISSUE THREAD

**Issue by ProFortniteGamer500** [V10lator/NUSspli#370]
i just got my wii u modded and got pretendo and NUSspli. I was downloading games i used to had on disc to digital on my usb using NUSspli. For some reason once my games where done i tried to play them but it would say it needs a update even though i updated them while downloading the game.  And gives me error codes saying something like the servers are in traffic. And a other one is when it said something about "Nintendo ID User game been deleted" or something. What should i do?

**Comment by ableto288** [comment]
Did you add [SigpatchesModuleWiiU](https://github.com/marco-calautti/SigpatchesModuleWiiU) to your aroma mod?

**Comment by ProFortniteGamer500** [comment]
I almost forgot about this. I have downloaded them. 

I love NUSspli

**Comment by Pearunicorn2** [comment]
what folder should I put Sigpatches in?

**Comment by Pearunicorn2** [comment]
I tried the wiiu/apps folder, and it showed up on the home screen, but when I loaded it, it said "There is a problem with the system memory." I then tried to download a game with NUSspli, and it gave me a red error message that said "The files might be corrupt."

**Comment by KingSkribbz** [comment]
> I tried the wiiu/apps folder, and it showed up on the home screen, but when I loaded it, it said "There is a problem with the system memory." I then tried to download a game with NUSspli, and it gave me a red error message that said "The files might be corrupt."

Try putting the file in ```/wiiu/environments/aroma/modules/setup/```

**Comment by shockasteroid** [comment]
> > I tried the wiiu/apps folder, and it showed up on the home screen, but when I loaded it, it said "There is a problem with the system memory." I then tried to download a game with NUSspli, and it gave me a red error message that said "The files might be corrupt."
> 
> Try putting the file in `/wiiu/environments/aroma/modules/setup/`

I've tried putting the folder in setup and it still keeps giving me the ID thing, what do I do?

**Comment by gio-xspan0** [comment]
Dead forum but what's the solution?
