### ISSUE TITLE
"This software cannot be used."

### ISSUE THREAD

**Issue by windnedr** [V10lator/NUSspli#375]
It says this when I try to open an installed app.
![2024-11-26_13 22 17 048_DRC](https://github.com/user-attachments/assets/9bee4f74-c085-4ee4-8cea-cfa7359ec310)

**Comment by WoutvanderAa** [comment]
same here, I hope someone knows how to fix it

**Comment by dariusarnold** [comment]
I think you are missing sig patches. Try installing the latest release from here https://github.com/marco-calautti/SigpatchesModuleWiiU into SD://wiiu/environments/aroma/modules/setup.
