### ISSUE TITLE
Error whilst installing a title on NUSspli

### ISSUE THREAD

**Issue by CoolBuzz21** [V10lator/NUSspli#38]
So there is an error that displays in red when I try to install a title saying,  **Internal error installing "/vol/app_sd/install/New Super Mario Bros.___ U [0005000010101e00]" Your Homebre Launcher Channel is probably outdated!**. In this case, I am using the homebrew laucher version 1.4 because 2.1 gives me an error. I am not sure what to do.

**Comment by V10lator** [comment]
Duplication of #35. To conlude what was told there: In case you use HBLC use https://github.com/GaryOderNichts/homebrew_launcher/releases/tag/v2.1_fix - else use the channel version of NUSspli.

**Comment by CoolBuzz21** [comment]
So I don't have Haxchi to install the HBL channel. So, how do I install the channel version of NUSspli? I have the files, but I'm not sure what to use to install it and where to actually place the files in the SD.
