### ISSUE TITLE
Crashes when I generate a fake title.tik

### ISSUE THREAD

**Issue by MaskedCat** [V10lator/NUSspli#39]
Whenever I try yo generate a title.tik file it just makes my Wii U crash and I can’t do anything.

**Comment by V10lator** [comment]
Thanks for the report. Some questions through:

- What's the version of NUSspli you are using?
- Channel or HBL version?
- Is it happening when you try to create a ticket for existig content (if so: For what content) or while downloading a title?

**Comment by MaskedCat** [comment]
• homebrew launcher v1.4
• NUSspli v1.32
• Existing content, and It does the same with every game : virtual console games or Wii U games is the same result (I tried Pokémon snap, super Mario 64, Mario kart DS and super Mario bros 3 for virtual console and twilight princess hd and ct treasure tracker)

**Comment by V10lator** [comment]
Thanks again, with this informations I'm able to recreate the issue but it's random for me. :)

**Comment by V10lator** [comment]
A possible fix has been handled to beta testers, so expect this to be fixed with the next release.
