### ISSUE TITLE
Crash after the online update from 1.32 debug to 1.33 (channel)

### ISSUE THREAD

**Issue by carcaschoi** [V10lator/NUSspli#41]
stuck on the installation finished green screen and stop responding 
I need to force poweroff wiiu

log: 
Wed 14 Jul 2021 15:59:54.670	NUSspli 1.32
Wed 14 Jul 2021 15:59:54.671	main: Checking thread stacks...
Wed 14 Jul 2021 15:59:54.671	main: Done!
Wed 14 Jul 2021 15:59:54.876	CC: d7b00402659ba2abd2cb0db27fa2b656
Wed 14 Jul 2021 15:59:54.880	Changed audio thread priority!
Wed 14 Jul 2021 15:59:55.080	libgui initialized!
Wed 14 Jul 2021 15:59:55.146	Changed main thread priority!
Wed 14 Jul 2021 15:59:55.179	RNG seeded!
Wed 14 Jul 2021 15:59:55.196	Rumble initialized!
Wed 14 Jul 2021 15:59:55.219	Network initialized!
Wed 14 Jul 2021 15:59:55.229	Socket optimizer running!
Wed 14 Jul 2021 15:59:55.229	Downloader initialized!
Wed 14 Jul 2021 15:59:55.262	cJSON initialized!
Wed 14 Jul 2021 15:59:55.296	Initializing config file...
Wed 14 Jul 2021 15:59:55.308	System language found: Japanese
Wed 14 Jul 2021 15:59:55.309	Config file loaded!
Wed 14 Jul 2021 15:59:55.329	SWKBD_Init()
Wed 14 Jul 2021 15:59:55.662	SWKBD initialized!
Wed 14 Jul 2021 15:59:55.696	MCP initialized!
Wed 14 Jul 2021 15:59:55.713	I/O thread initialized!
Wed 14 Jul 2021 15:59:55.713	I/O queue running!
Wed 14 Jul 2021 15:59:55.737	main(): Checking thread stacks...
Wed 14 Jul 2021 15:59:55.740	main(): Done!
Wed 14 Jul 2021 15:59:55.763	Download URL: http://napi.nbg01.v10lator.de/v2/s?t=c
Wed 14 Jul 2021 15:59:55.763	Download PATH: <RAM>
Wed 14 Jul 2021 15:59:55.764	Calling curl_easy_perform()
Wed 14 Jul 2021 16:00:27.600	curl_easy_perform() returned: 6
Wed 14 Jul 2021 16:00:27.601	curl_easy_perform returned an error: Couldn't resolve host 'napi.nbg01.v10lator.de' (6)
File: <RAM>

Wed 14 Jul 2021 16:00:27.601	Error frame
Wed 14 Jul 2021 16:00:36.036	Download URL: http://napi.nbg01.v10lator.de/v2/s?t=c
Wed 14 Jul 2021 16:00:36.037	Download PATH: <RAM>
Wed 14 Jul 2021 16:00:36.038	Calling curl_easy_perform()
Wed 14 Jul 2021 16:00:36.388	curl_easy_perform() returned: 0
Wed 14 Jul 2021 16:00:36.388	curl_easy_perform executed successfully
Wed 14 Jul 2021 16:00:36.389	The download returned: 200
Wed 14 Jul 2021 16:00:36.390	The file was downloaded successfully
Wed 14 Jul 2021 16:00:36.391	Download JSON finished!
Wed 14 Jul 2021 16:00:45.462	Home key disabled!
Wed 14 Jul 2021 16:00:45.466	Path "fs:/vol/external01/NUSspli_temp/" not found!
Wed 14 Jul 2021 16:00:45.898	Download URL: http://napi.nbg01.v10lator.de/v2/d?t=c
Wed 14 Jul 2021 16:00:45.899	Download PATH: <RAM>
Wed 14 Jul 2021 16:00:45.899	Calling curl_easy_perform()
Wed 14 Jul 2021 16:01:04.326	curl_easy_perform() returned: 0
Wed 14 Jul 2021 16:01:04.435	curl_easy_perform executed successfully
Wed 14 Jul 2021 16:01:04.436	The download returned: 200
Wed 14 Jul 2021 16:01:04.437	The file was downloaded successfully
Wed 14 Jul 2021 16:01:04.437	Download NUSspli.zip finished!
Wed 14 Jul 2021 16:01:05.741	Flushing...
Wed 14 Jul 2021 16:01:06.500	Flushing...
Wed 14 Jul 2021 16:01:06.506	NUSspli path:  fs:/vol/external01/NUSspli_temp/NUSspli (39)
Wed 14 Jul 2021 16:01:06.507	MCP Path:      /vol/app_sd/NUSspli_temp/NUSspli (32)
Wed 14 Jul 2021 16:01:14.708	Home key enabled!
Wed 14 Jul 2021 16:01:14.709	Installation finished!
Wed 14 Jul 2021 16:01:15.710	Rumble thread: Checking thread stacks...
Wed 14 Jul 2021 16:01:15.711	Rumble thread: Done!
Wed 14 Jul 2021 16:01:19.485	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000008.h3
Wed 14 Jul 2021 16:01:19.496	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000002.app
Wed 14 Jul 2021 16:01:19.507	Removing fs:/vol/external01/NUSspli_temp/NUSspli/title.tmd
Wed 14 Jul 2021 16:01:19.517	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000001.app
Wed 14 Jul 2021 16:01:19.528	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000004.h3
Wed 14 Jul 2021 16:01:19.540	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000005.app
Wed 14 Jul 2021 16:01:19.555	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000006.h3
Wed 14 Jul 2021 16:01:19.567	Removing fs:/vol/external01/NUSspli_temp/NUSspli/title.tik
Wed 14 Jul 2021 16:01:19.578	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000003.app
Wed 14 Jul 2021 16:01:19.589	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000008.app
Wed 14 Jul 2021 16:01:19.613	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000004.app
Wed 14 Jul 2021 16:01:19.728	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000007.app
Wed 14 Jul 2021 16:01:19.747	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000006.app
Wed 14 Jul 2021 16:01:19.803	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000003.h3
Wed 14 Jul 2021 16:01:19.818	Removing fs:/vol/external01/NUSspli_temp/NUSspli/title.cert
Wed 14 Jul 2021 16:01:19.830	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000005.h3
Wed 14 Jul 2021 16:01:19.841	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000000.app
Wed 14 Jul 2021 16:01:19.852	Removing fs:/vol/external01/NUSspli_temp/NUSspli
Wed 14 Jul 2021 16:01:19.860	Removing fs:/vol/external01/NUSspli_temp
Wed 14 Jul 2021 16:01:19.868	I/O thread returned: 0
Wed 14 Jul 2021 16:01:19.868	I/O thread closed
Wed 14 Jul 2021 16:01:19.901	MCP closed
Wed 14 Jul 2021 16:01:19.912	SWKBD font: Checking thread stacks...
Wed 14 Jul 2021 16:01:19.913	SWKBD font: Done!
Wed 14 Jul 2021 16:01:19.913	SWKBD closed
Wed 14 Jul 2021 16:01:19.915	Socket optimizer returned: 0
Wed 14 Jul 2021 16:01:19.916	Network closed
Wed 14 Jul 2021 16:01:19.916	Rumble thread: Checking thread stacks...
Wed 14 Jul 2021 16:01:19.917	Rumble thread: Done!
Wed 14 Jul 2021 16:01:19.918	Rumble closed

**Comment by V10lator** [comment]
Is this before or while showing the Goodbye screen?

**Comment by carcaschoi** [comment]
before

**Comment by V10lator** [comment]
Please test https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.34-ALPHA2-Channel-DEBUG.zip and grab a new log in case the bug hasn't been fixed already.

**Comment by carcaschoi** [comment]
I think it is the bug of the auto update function. Do You need to pull a new update so that I can test it ?

**Comment by V10lator** [comment]
Try this one: https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.0-ALPHA99-Channel-DEBUG.zip - the versions number has been faked so you should get an update message ;)

**Comment by carcaschoi** [comment]
Error: The channel version of Nusspli is deprecated

log:
Thu 15 Jul 2021 15:09:27.877	NUSspli 1.0-ALPHA99
Thu 15 Jul 2021 15:09:27.883	main: Checking thread stacks...
Thu 15 Jul 2021 15:09:27.884	main: Done!
Thu 15 Jul 2021 15:09:28.089	CC: d7b00402659ba2abd2cb0db27fa2b656
Thu 15 Jul 2021 15:09:28.102	Changed audio thread priority!
Thu 15 Jul 2021 15:09:28.320	libgui initialized!
Thu 15 Jul 2021 15:09:28.385	Changed main thread priority!
Thu 15 Jul 2021 15:09:28.419	RNG seeded!
Thu 15 Jul 2021 15:09:28.435	Rumble initialized!
Thu 15 Jul 2021 15:09:28.458	Network initialized!
Thu 15 Jul 2021 15:09:28.469	Socket optimizer running!
Thu 15 Jul 2021 15:09:28.469	Downloader initialized!
Thu 15 Jul 2021 15:09:28.502	cJSON initialized!
Thu 15 Jul 2021 15:09:28.535	Initializing config file...
Thu 15 Jul 2021 15:09:28.548	System language found: Japanese
Thu 15 Jul 2021 15:09:28.549	Config file loaded!
Thu 15 Jul 2021 15:09:28.569	SWKBD_Init()
Thu 15 Jul 2021 15:09:28.905	SWKBD initialized!
Thu 15 Jul 2021 15:09:28.936	MCP initialized!
Thu 15 Jul 2021 15:09:28.953	I/O thread initialized!
Thu 15 Jul 2021 15:09:28.953	I/O queue running!
Thu 15 Jul 2021 15:09:28.977	main(): Checking thread stacks...
Thu 15 Jul 2021 15:09:28.980	main(): Done!
Thu 15 Jul 2021 15:09:29.002	Download URL: http://napi.nbg01.v10lator.de/v2/s?t=c
Thu 15 Jul 2021 15:09:29.003	Download PATH: <RAM>
Thu 15 Jul 2021 15:09:29.004	Calling curl_easy_perform()
Thu 15 Jul 2021 15:09:29.435	curl_easy_perform() returned: 0
Thu 15 Jul 2021 15:09:29.436	curl_easy_perform executed successfully
Thu 15 Jul 2021 15:09:29.436	The download returned: 200
Thu 15 Jul 2021 15:09:29.437	The file was downloaded successfully
Thu 15 Jul 2021 15:09:29.438	Download JSON finished!
Thu 15 Jul 2021 15:09:29.453	Error frame

**Comment by V10lator** [comment]
I spoofed the version to one no longer supported by the update checker. Sorry for that. Anyway, try this one instead: https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.23-ALPHA99-Channel-DEBUG.zip

**Comment by carcaschoi** [comment]
> I spoofed the version to one no longer supported by the update checker. Sorry for that. Anyway, try this one instead: https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.23-ALPHA99-Channel-DEBUG.zip

Same error: The channel version of Nusspli is deprecated

**Comment by V10lator** [comment]
I'm so sorry...This time I confirmed that it really receives the update: https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.24-ALPHA99-Channel-DEBUG.zip

**Comment by carcaschoi** [comment]
Fixed

log: 
Thu 15 Jul 2021 21:50:35.353	NUSspli 1.24-ALPHA99
Thu 15 Jul 2021 21:50:35.357	main: Checking thread stacks...
Thu 15 Jul 2021 21:50:35.358	main: Done!
Thu 15 Jul 2021 21:50:35.563	CC: d7b00402659ba2abd2cb0db27fa2b656
Thu 15 Jul 2021 21:50:35.569	Changed audio thread priority!
Thu 15 Jul 2021 21:50:35.791	libgui initialized!
Thu 15 Jul 2021 21:50:35.862	Changed main thread priority!
Thu 15 Jul 2021 21:50:35.894	RNG seeded!
Thu 15 Jul 2021 21:50:35.911	Rumble initialized!
Thu 15 Jul 2021 21:50:35.934	Network initialized!
Thu 15 Jul 2021 21:50:35.944	Socket optimizer running!
Thu 15 Jul 2021 21:50:35.944	Downloader initialized!
Thu 15 Jul 2021 21:50:35.978	cJSON initialized!
Thu 15 Jul 2021 21:50:36.012	Initializing config file...
Thu 15 Jul 2021 21:50:36.025	System language found: Japanese
Thu 15 Jul 2021 21:50:36.026	Config file loaded!
Thu 15 Jul 2021 21:50:36.045	SWKBD_Init()
Thu 15 Jul 2021 21:50:36.377	SWKBD initialized!
Thu 15 Jul 2021 21:50:36.412	MCP initialized!
Thu 15 Jul 2021 21:50:36.428	I/O thread initialized!
Thu 15 Jul 2021 21:50:36.428	I/O queue running!
Thu 15 Jul 2021 21:50:36.453	main(): Checking thread stacks...
Thu 15 Jul 2021 21:50:36.456	main(): Done!
Thu 15 Jul 2021 21:50:36.478	Download URL: http://napi.nbg01.v10lator.de/v2/s?t=c
Thu 15 Jul 2021 21:50:36.479	Download PATH: <RAM>
Thu 15 Jul 2021 21:50:36.480	Calling curl_easy_perform()
Thu 15 Jul 2021 21:50:37.123	curl_easy_perform() returned: 0
Thu 15 Jul 2021 21:50:37.124	curl_easy_perform executed successfully
Thu 15 Jul 2021 21:50:37.127	The download returned: 200
Thu 15 Jul 2021 21:50:37.127	The file was downloaded successfully
Thu 15 Jul 2021 21:50:37.128	Download JSON finished!
Thu 15 Jul 2021 21:50:39.698	Home key disabled!
Thu 15 Jul 2021 21:50:39.701	Path "fs:/vol/external01/NUSspli_temp/" not found!
Thu 15 Jul 2021 21:50:40.057	Download URL: http://napi.nbg01.v10lator.de/v2/d?t=c
Thu 15 Jul 2021 21:50:40.058	Download PATH: <RAM>
Thu 15 Jul 2021 21:50:40.059	Calling curl_easy_perform()
Thu 15 Jul 2021 21:51:09.751	curl_easy_perform() returned: 0
Thu 15 Jul 2021 21:51:09.861	curl_easy_perform executed successfully
Thu 15 Jul 2021 21:51:09.863	The download returned: 200
Thu 15 Jul 2021 21:51:09.863	The file was downloaded successfully
Thu 15 Jul 2021 21:51:09.864	Download NUSspli.zip finished!
Thu 15 Jul 2021 21:51:11.140	Flushing...
Thu 15 Jul 2021 21:51:11.981	Flushing...
Thu 15 Jul 2021 21:51:11.986	NUSspli path:  fs:/vol/external01/NUSspli_temp/NUSspli (39)
Thu 15 Jul 2021 21:51:11.987	MCP Path:      /vol/app_sd/NUSspli_temp/NUSspli (32)
Thu 15 Jul 2021 21:51:19.638	Home key enabled!
Thu 15 Jul 2021 21:51:19.639	Installation finished!
Thu 15 Jul 2021 21:51:20.639	Rumble thread: Checking thread stacks...
Thu 15 Jul 2021 21:51:20.641	Rumble thread: Done!
Thu 15 Jul 2021 21:51:28.102	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000008.h3
Thu 15 Jul 2021 21:51:28.113	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000002.app
Thu 15 Jul 2021 21:51:28.124	Removing fs:/vol/external01/NUSspli_temp/NUSspli/title.tmd
Thu 15 Jul 2021 21:51:28.135	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000001.app
Thu 15 Jul 2021 21:51:28.145	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000004.h3
Thu 15 Jul 2021 21:51:28.156	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000005.app
Thu 15 Jul 2021 21:51:28.167	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000006.h3
Thu 15 Jul 2021 21:51:28.178	Removing fs:/vol/external01/NUSspli_temp/NUSspli/title.tik
Thu 15 Jul 2021 21:51:28.189	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000003.app
Thu 15 Jul 2021 21:51:28.201	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000008.app
Thu 15 Jul 2021 21:51:28.329	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000004.app
Thu 15 Jul 2021 21:51:28.391	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000007.app
Thu 15 Jul 2021 21:51:28.413	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000006.app
Thu 15 Jul 2021 21:51:28.425	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000003.h3
Thu 15 Jul 2021 21:51:28.436	Removing fs:/vol/external01/NUSspli_temp/NUSspli/title.cert
Thu 15 Jul 2021 21:51:28.448	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000005.h3
Thu 15 Jul 2021 21:51:28.459	Removing fs:/vol/external01/NUSspli_temp/NUSspli/00000000.app
Thu 15 Jul 2021 21:51:28.469	Removing fs:/vol/external01/NUSspli_temp/NUSspli
Thu 15 Jul 2021 21:51:28.515	Removing fs:/vol/external01/NUSspli_temp
Thu 15 Jul 2021 21:51:28.523	I/O thread returned: 0
Thu 15 Jul 2021 21:51:28.523	I/O thread closed
Thu 15 Jul 2021 21:51:28.556	MCP closed
Thu 15 Jul 2021 21:51:28.563	SWKBD font: Checking thread stacks...
Thu 15 Jul 2021 21:51:28.564	SWKBD font: Done!
Thu 15 Jul 2021 21:51:28.565	SWKBD closed
Thu 15 Jul 2021 21:51:28.566	Socket optimizer returned: 0
Thu 15 Jul 2021 21:51:28.567	Network closed
Thu 15 Jul 2021 21:51:28.568	Rumble thread: Checking thread stacks...
Thu 15 Jul 2021 21:51:28.569	Rumble thread: Done!
Thu 15 Jul 2021 21:51:28.569	Rumble closed
Thu 15 Jul 2021 21:51:28.569	Starting new frame
Thu 15 Jul 2021 21:51:28.570	Opening PNG file
Thu 15 Jul 2021 21:51:28.572	Grabbing filesize
Thu 15 Jul 2021 21:51:28.574	Allocating memory
Thu 15 Jul 2021 21:51:28.574	Loading PNG file into memory
Thu 15 Jul 2021 21:51:28.584	Creating texture
Thu 15 Jul 2021 21:51:28.619	Attaching texture to frame
Thu 15 Jul 2021 21:51:28.619	Closing file
Thu 15 Jul 2021 21:51:28.620	Drawing frame
Thu 15 Jul 2021 21:51:28.621	Showing frame
Thu 15 Jul 2021 21:51:28.630	Stopping renderer
Thu 15 Jul 2021 21:51:28.682	libgui closed
Thu 15 Jul 2021 21:51:28.683	main: Checking thread stacks...
Thu 15 Jul 2021 21:51:28.684	main: Done!
Thu 15 Jul 2021 21:51:28.684	Bye!

**Comment by carcaschoi** [comment]
It also fix the bug that Nusspli stuck on the main screen after updating. Nice job!
