### ISSUE TITLE
Crash after install the channel with wup_installer_gx2

### ISSUE THREAD

**Issue by carcaschoi** [V10lator/NUSspli#43]
After I install the channel with the wup_installer_gx2 hbl version. It will stuck on the black screen after I press the ok button
The nusspli package will install successfully but I need to force poweroff wiiu everytime 

I try to install another game with wup_installer_gx2 and doesnot have this problem

**Comment by V10lator** [comment]
Is it the same with [WUP Installer Y-mod](https://github.com/Yardape8000/wupinstaller/releases/tag/y1.3)?

**Comment by carcaschoi** [comment]
No problem with WUP Installer Y-mod

**Comment by V10lator** [comment]
So most likely a WUP Installer GX2 bug. From personal experience as well as reviewing the sources I wouldn't recommending using GX2 at all, Y-Mod is much more stable.
