### ISSUE TITLE
1.34 freezes on load 

### ISSUE THREAD

**Issue by dannyzumwalt** [V10lator/NUSspli#44]
New 1.34 stuck at eyeball lid screen after update. Tried restarting. Still getting stuck at blue splash screen. 

I’m on 5.5.5 with Haxchi

edit: this was after an online update from 1.32 -> 1.34. I see there is a possibly related bug report after an update to earlier versions. https://github.com/V10lator/NUSspli/issues/37

**Comment by V10lator** [comment]
What do you mean with eyeball lit screen?

For the splash issue you could try the following:
1. Use FTPiiU Everywhere to delete all files at `/storage_slc/logs/`.
2. Recreate the splash screen issue.
3. Send me the file `/storage_slc/logs/1.log`.

**Comment by dannyzumwalt** [comment]
Typo.. the splash screen. 

I see a 1.35 hot fix just came out. Will give it a try. For what it's worth 1.33 loads fine.

**Comment by CarlosNunezMX** [comment]
So i've that bug in 1.35 and i attach my log.
Good day :)
[1.log](https://github.com/V10lator/NUSspli/files/6825954/1.log)

**Comment by V10lator** [comment]
Thanks for the log. While it doesn't look like it crashed on the splash screen but on the title browser screen it's still interresting.

**Comment by V10lator** [comment]
Should be fixed.
