### ISSUE TITLE
poweroff issue (channel)

### ISSUE THREAD

**Issue by carcaschoi** [V10lator/NUSspli#45]
Version of Nusspli: 1.35

If I press the poweroff button on the nusspli main screen,it will stuck on the goodbye screen. I need to force poweroff it

**Comment by carcaschoi** [comment]
log:
Fri 16 Jul 2021 15:59:16.708	NUSspli 1.35
Fri 16 Jul 2021 15:59:16.715	main: Checking thread stacks...
Fri 16 Jul 2021 15:59:16.716	main: Done!
Fri 16 Jul 2021 15:59:16.921	CC: d7b00402659ba2abd2cb0db27fa2b656
Fri 16 Jul 2021 15:59:16.929	Changed audio thread priority!
Fri 16 Jul 2021 15:59:17.143	libgui initialized!
Fri 16 Jul 2021 15:59:17.208	Changed main thread priority!
Fri 16 Jul 2021 15:59:17.241	RNG seeded!
Fri 16 Jul 2021 15:59:17.258	Rumble initialized!
Fri 16 Jul 2021 15:59:17.281	Network initialized!
Fri 16 Jul 2021 15:59:17.291	Socket optimizer running!
Fri 16 Jul 2021 15:59:17.291	Downloader initialized!
Fri 16 Jul 2021 15:59:17.325	cJSON initialized!
Fri 16 Jul 2021 15:59:17.359	Initializing config file...
Fri 16 Jul 2021 15:59:17.373	System language found: Japanese
Fri 16 Jul 2021 15:59:17.373	Config file loaded!
Fri 16 Jul 2021 15:59:17.391	SWKBD_Init()
Fri 16 Jul 2021 15:59:17.724	SWKBD initialized!
Fri 16 Jul 2021 15:59:17.759	MCP initialized!
Fri 16 Jul 2021 15:59:17.775	I/O thread initialized!
Fri 16 Jul 2021 15:59:17.775	I/O queue running!
Fri 16 Jul 2021 15:59:17.800	main(): Checking thread stacks...
Fri 16 Jul 2021 15:59:17.803	main(): Done!
Fri 16 Jul 2021 15:59:17.825	Download URL: http://napi.nbg01.v10lator.de/v2/s?t=c
Fri 16 Jul 2021 15:59:17.826	Download PATH: <RAM>
Fri 16 Jul 2021 15:59:17.827	Calling curl_easy_perform()
Fri 16 Jul 2021 15:59:18.196	curl_easy_perform() returned: 0
Fri 16 Jul 2021 15:59:18.197	curl_easy_perform executed successfully
Fri 16 Jul 2021 15:59:18.198	The download returned: 200
Fri 16 Jul 2021 15:59:18.198	The file was downloaded successfully
Fri 16 Jul 2021 15:59:18.199	Download JSON finished!
Fri 16 Jul 2021 15:59:18.209	Newest version!
Fri 16 Jul 2021 15:59:18.226	Download URL: http://napi.nbg01.v10lator.de/v2/t
Fri 16 Jul 2021 15:59:18.226	Download PATH: <RAM>
Fri 16 Jul 2021 15:59:18.227	Calling curl_easy_perform()
Fri 16 Jul 2021 15:59:19.229	curl_easy_perform() returned: 0
Fri 16 Jul 2021 15:59:19.231	curl_easy_perform executed successfully
Fri 16 Jul 2021 15:59:19.232	The download returned: 200
Fri 16 Jul 2021 15:59:19.232	The file was downloaded successfully
Fri 16 Jul 2021 15:59:19.233	Download JSON finished!
Fri 16 Jul 2021 15:59:19.308	title database parsed!
Fri 16 Jul 2021 15:59:19.309	3631 titles parsed
Fri 16 Jul 2021 15:59:19.309	main: Checking thread stacks...
Fri 16 Jul 2021 15:59:19.312	main: Done!
Fri 16 Jul 2021 15:59:28.202	Starting new frame
Fri 16 Jul 2021 15:59:28.203	Opening PNG file
Fri 16 Jul 2021 15:59:28.205	Grabbing filesize
Fri 16 Jul 2021 15:59:28.207	Allocating memory
Fri 16 Jul 2021 15:59:28.207	Loading PNG file into memory
Fri 16 Jul 2021 15:59:28.213	Creating texture
Fri 16 Jul 2021 15:59:28.255	Attaching texture to frame
Fri 16 Jul 2021 15:59:28.256	Closing file
Fri 16 Jul 2021 15:59:28.257	Drawing frame
Fri 16 Jul 2021 15:59:28.258	Showing frame
Fri 16 Jul 2021 15:59:28.269	Stopping renderer

**Comment by V10lator** [comment]
Thanks for the report. this time it crashes while showing the goodbye screen, right? Sadly the debug log doesn't cover this, so please try to recreate the log with this one: https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.36-ALPHA1-Channel-DEBUG.zip

**Comment by carcaschoi** [comment]
Fri 16 Jul 2021 16:21:23.017	NUSspli 1.36-ALPHA1
Fri 16 Jul 2021 16:21:23.023	main: Checking thread stacks...
Fri 16 Jul 2021 16:21:23.024	main: Done!
Fri 16 Jul 2021 16:21:23.229	CC: d7b00402659ba2abd2cb0db27fa2b656
Fri 16 Jul 2021 16:21:23.237	Changed audio thread priority!
Fri 16 Jul 2021 16:21:23.469	libgui initialized!
Fri 16 Jul 2021 16:21:23.532	Changed main thread priority!
Fri 16 Jul 2021 16:21:23.565	RNG seeded!
Fri 16 Jul 2021 16:21:23.582	Rumble initialized!
Fri 16 Jul 2021 16:21:23.606	Network initialized!
Fri 16 Jul 2021 16:21:23.616	Socket optimizer running!
Fri 16 Jul 2021 16:21:23.616	Downloader initialized!
Fri 16 Jul 2021 16:21:23.649	cJSON initialized!
Fri 16 Jul 2021 16:21:23.682	Initializing config file...
Fri 16 Jul 2021 16:21:23.696	System language found: Japanese
Fri 16 Jul 2021 16:21:23.696	Config file loaded!
Fri 16 Jul 2021 16:21:23.716	SWKBD_Init()
Fri 16 Jul 2021 16:21:24.052	SWKBD initialized!
Fri 16 Jul 2021 16:21:24.083	MCP initialized!
Fri 16 Jul 2021 16:21:24.099	I/O thread initialized!
Fri 16 Jul 2021 16:21:24.099	I/O queue running!
Fri 16 Jul 2021 16:21:24.124	main(): Checking thread stacks...
Fri 16 Jul 2021 16:21:24.127	main(): Done!
Fri 16 Jul 2021 16:21:24.149	Download URL: http://napi.nbg01.v10lator.de/v2/s?t=c
Fri 16 Jul 2021 16:21:24.150	Download PATH: <RAM>
Fri 16 Jul 2021 16:21:24.152	Calling curl_easy_perform()
Fri 16 Jul 2021 16:21:24.786	curl_easy_perform() returned: 0
Fri 16 Jul 2021 16:21:24.787	curl_easy_perform executed successfully
Fri 16 Jul 2021 16:21:24.788	The download returned: 200
Fri 16 Jul 2021 16:21:24.788	The file was downloaded successfully
Fri 16 Jul 2021 16:21:24.789	Download JSON finished!
Fri 16 Jul 2021 16:21:24.800	Newest version!
Fri 16 Jul 2021 16:21:24.817	Download URL: http://napi.nbg01.v10lator.de/v2/t
Fri 16 Jul 2021 16:21:24.817	Download PATH: <RAM>
Fri 16 Jul 2021 16:21:24.818	Calling curl_easy_perform()
Fri 16 Jul 2021 16:21:25.899	curl_easy_perform() returned: 0
Fri 16 Jul 2021 16:21:25.900	curl_easy_perform executed successfully
Fri 16 Jul 2021 16:21:25.901	The download returned: 200
Fri 16 Jul 2021 16:21:25.902	The file was downloaded successfully
Fri 16 Jul 2021 16:21:25.902	Download JSON finished!
Fri 16 Jul 2021 16:21:25.982	title database parsed!
Fri 16 Jul 2021 16:21:25.982	3631 titles parsed
Fri 16 Jul 2021 16:21:25.983	main: Checking thread stacks...
Fri 16 Jul 2021 16:21:25.984	main: Done!
Fri 16 Jul 2021 16:22:00.035	Starting new frame
Fri 16 Jul 2021 16:22:00.036	Opening PNG file
Fri 16 Jul 2021 16:22:00.038	Grabbing filesize
Fri 16 Jul 2021 16:22:00.040	Allocating memory
Fri 16 Jul 2021 16:22:00.040	Loading PNG file into memory
Fri 16 Jul 2021 16:22:00.046	Creating texture
Fri 16 Jul 2021 16:22:00.088	Attaching texture to frame
Fri 16 Jul 2021 16:22:00.088	Closing file
Fri 16 Jul 2021 16:22:00.089	Drawing frame
Fri 16 Jul 2021 16:22:00.091	Showing frame
Fri 16 Jul 2021 16:22:00.102	Stopping renderer
Fri 16 Jul 2021 16:22:00.103	Clearing frame
Fri 16 Jul 2021 16:22:00.103	Removing error overlay
Fri 16 Jul 2021 16:22:00.104	Deleting texture blobs
Fri 16 Jul 2021 16:22:00.106	Deleting surface
Fri 16 Jul 2021 16:22:00.106	Deleting renderer
Fri 16 Jul 2021 16:22:00.136	Deleting goodbye screen blobs
Fri 16 Jul 2021 16:22:00.137	Deleting background music
Fri 16 Jul 2021 16:22:00.158	Deleting background music blob
Fri 16 Jul 2021 16:22:00.158	Releasing libgui
