### ISSUE TITLE
"DLC/E-Shop require Sig Patches" when having two HDDs connected (one hidden with UStealth) and trying to install to USB

### ISSUE THREAD

**Issue by eku** [V10lator/NUSspli#46]
Running NUSspli 1.35 (HBL version) to install E-Shop version of `00050000101D0600` gives me `DLC/E-Shop require Sig Patches` message. Mocha has been started via browser hax.

WUP Installer GX2 installs it without any problem to external USB disk drive.

**Comment by V10lator** [comment]
Thanks for the report. Sadly I can't recreate this on first try, so some questions:

- Are you downloading to SD or USB?
- Are you trying to install to USB or NAND?

**Comment by V10lator** [comment]
Another thing that comes to my mind is that the current stable version is using a buggy and deprecated rendering backend causing the weirdest things. So please try again with this one: https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.36-BETA1-Channel-DEBUG.zip

**Comment by carcaschoi** [comment]
> Running NUSspli 1.35 (HBC version) to install E-Shop version of `00050000101D0600` gives me `DLC/E-Shop require Sig Patches` message. Mocha has been started via browser hax.
> 
> WUP Installer GX2 installs it without any problem to external USB disk drive.

Channel version or HBL version？

**Comment by V10lator** [comment]
I guess HBC is a typo, so HBL.

**Comment by eku** [comment]
@V10lator  wrote:
> Thanks for the report. Sadly I can't recreate this on first try, so some questions:
>     * Are you downloading to SD or USB?
>     * Are you trying to install to USB or NAND?

@eku wrote:
> WUP Installer GX2 installs it without any problem to external USB disk drive.

So, the files are already on SD card and going to be installed to USB.

**Comment by V10lator** [comment]
I see. Sadly no one of the team seems to be able to recreate this issue but we're all using 1.36-BETA1. So again: Could you try that one and report back if it works?

**Comment by V10lator** [comment]
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.36-BETA1-Channel-DEBUG.zip
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.36-BETA1-HBL-DEBUG.zip

**Comment by carcaschoi** [comment]
Since I have made a video of this app on youtube, there is a person comment that he has the same issue. The different is he is using cold boot haxchi

**Comment by eku** [comment]
@V10lator `NUSspli-1.36-BETA1-HBL-DEBUG.zip` shows the same problem. Is there any debug output written I could provide?

**Comment by V10lator** [comment]
> When I remove the disk hidden with UStealth from the second USB port, the installation works with NUSspli.

That's good to know, thank you. Probably the HDD detection codes are wrong.

> Is there any debug output written I could provide?

No, but thanks for asking. :)

**Comment by V10lator** [comment]
That error is weird as USB codes didn't change since 1.18. So we need another way to track this down. What's the last working version?

**Comment by V10lator** [comment]
Also feel free to hop on our Discord ( https://discord.gg/B8ZBd6mrnV ) and DM me there. What we will do now is bisecting ( https://git-scm.com/docs/git-bisect ) but that's a slow process. Direct communication might make it a bit faster thrrough.

**Comment by eku** [comment]
Discord won't let me write without an account. So let's stick to GitHub, I already have one there. I would also accept IRC.

Unfortunately, I can't say from which version on it doesn't work anymore, because I update more often but don't install programs from the e-shop with every version. But I could try older versions if it serves the cause. They are still available in the release tab. It will take some time, so please don't get impatient.

I would like to take this opportunity to note the following. NUSspli reinstalls even if the software is already installed in the version and on the medium (USB/NAND). At least a confirmation would be useful to still be able to cancel an accidental selection and installation.

**Comment by V10lator** [comment]
> So let's stick to GitHub

Allright.

> But I could try older versions if it serves the cause

That would help a lot.

> It will take some time, so please don't get impatient.

I won't, don't worry. :)

> I would like to take this opportunity to note the following

Please open a new bug report for this, else chances are high that I will forget about it. Other than that NUSpli and WUP installer are doing things pretty similiar - IIRC there is no confirmation screen at WUP installer. Also there are some hints already (checkmark at the title browser, asking if you would like to uninstall at the confirmation screen). Keep this in mind when making the new report, so tell in detail what confirmation exactly you would like to see.

**Comment by eku** [comment]
I have tested different versions one after the other and none of them could install content from sd:/install to usb:/ as long as a drive hidden by UStealth is connected on the second USB port.
```
Version 1.18-1.20 : Possible USB error
Version 1.21-1.36 : DLC/E-Shop requre Sig Patch
```
The files a pre-downloaded. I just enter NUSspli, press X for install content and select one of the folder and press A to install to USB. Verfication of files is fine, but installation failes.

**Comment by V10lator** [comment]
https://github.com/V10lator/NUSspli/issues/17#issuecomment-817147693

So please retest with 1.18-ALPHA1: [NUSspli-1.18-ALPHA1-HBL-DEBUG.zip](https://github.com/V10lator/NUSspli/files/6951121/NUSspli-1.18-ALPHA1-HBL-DEBUG.zip)

If it doesn't work this time please confirm it works with the UStealth HDD not attached to the Wii U and if that also fails please try with WUP Installer Y-Mod.

**Comment by eku** [comment]
@V10lator the proviced NUSspli-1.18-ALPHA1-HBL-DEBUG.zip does not contain the binary, only the icon and meta files.

Anyway, I removed the second HDD and NUSspli v1.36 installs the content without any problems.

**Comment by eku** [comment]
Is there anything I can do to move the issue forward in a positive way? In the end, it is because of a library from the devKitPro that returns the wrong drive to. Just a guess, as I have no knowledge in this regard.

**Comment by V10lator** [comment]
Please test one of these:
- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.38-ALPHA4-Aroma-DEBUG.zip
- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.38-ALPHA4-Channel-DEBUG.zip
- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.38-ALPHA4-HBL-DEBUG.zip

**Comment by V10lator** [comment]
Please also test:
- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.38-BETA2-Aroma-DEBUG.zip
- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.38-BETA2-Channel-DEBUG.zip
- https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.38-BETA2-HBL-DEBUG.zip

Then tell me what works better, ALPHA4 or BETA2. Also try things like swapping discs, please.

**Comment by V10lator** [comment]
Please test v1.38 instead o v1.38-BETA2.. So test 1.38-ALPHA4 and 1.38.

**Comment by eku** [comment]
v1.34APLPHA4 still the same error message.
v1.39 different error message "Error opening USB device".
Since I tested the HBL debug version is there any debug log I could provide?

**Comment by V10lator** [comment]
ALPHA4 should behave exactly like WUP Installer. Are you sure WUP Installer works while ALPHA4 doesn't?

**Comment by eku** [comment]
Both WUP Installer and NUSspli fail to install if second disk drive is connected. Do you think that the problem can be solved?

**Comment by V10lator** [comment]
Please test one of
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.40-ALPHA1-Aroma-DEBUG.zip
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.40-ALPHA1-Channel-DEBUG.zip
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.40-ALPHA1-HBL-DEBUG.zip

**Comment by V10lator** [comment]
Alo test one of
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.40-ALPHA1-Aroma-DEBUG.zip
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.40-ALPHA1-Channel-DEBUG.zip
https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.40-ALPHA1-HBL-DEBUG.zip
please. If neither ALPHA1 nor ALPHA2 fix the issue I'm out of ideas.

**Comment by V10lator** [comment]
Great, thank you. We Just reverse engineered some Cafe OS stuff by try and error. :)

**Comment by V10lator** [comment]
Cleaning this up cause there are still a lot of people trying to download the linked test versions.
