### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by ThatOneVideoGamer** [V10lator/NUSspli#48]
Saw that someone else had this but didn't provide any information so here's a new one

Downloading a game will result in a Network error every time without fail, it says that the router may have turned off but no other devices have disconnected.

Using NUSspli-1.36-HBL.zip

Currently testing other versions to see how far back the issue goes

Game being used to test this is Bayonetta (USA)

**Comment by V10lator** [comment]
Hi and thanks for the report. Are you testing via WLAN or cable (LAN) ? In case of the former: The WLAN connection of the Wii U is weak. Please do not put any metal things on top of the Wii U and try to move it closer to the router, then retest.

**Comment by ThatOneVideoGamer** [comment]
> Hi and thanks for the report. Are you testing via WLAN or cable (LAN) ? In case of the former: The WLAN connection of the Wii U is weak. Please do not put any metal things on top of the Wii U and try to move it closer to the router, then retest.

I am using WLAN, I can see if a wired connection solves the issue.
I have no metal on the Wii U
