### ISSUE TITLE
NUSspli just turns itself of in the middle of a download

### ISSUE THREAD

**Issue by lemonaded865** [V10lator/NUSspli#49]
After a while of downloading it just shows the goodbye page and I cant do anything for a while then about a minute later the console turns off

**Comment by V10lator** [comment]
Should be fixed with v1.37. Please reopen in case it's not.

**Comment by tristanyeom** [comment]
I'm having the same problem with the channel version on v1.37. I'm going to try the HBL version now.

**Comment by Korozin** [comment]
To be fair you shouldn't even be on v1.37 as to revieve full support you should be on the latest version, which as of the moment the latest official release is v1.95 with v1.96 being an un-official option.
