### ISSUE TITLE
Application locks up when curl_easy_perform returns CURLE_PARTIAL_FILE

### ISSUE THREAD

**Issue by jhaye** [V10lator/NUSspli#50]
The exact wording that is displayed is: "curl_easy_perform returned a non-valid value: 18".

The application displays further actions that I could take:
* Press Y to retry
* Press B to return

This however isn't possible no matter what button I press, or how I press (holding, repeated pressing). Only way to get out of this state is to power off the console manually.

---

This is on HBL 2.1 and NUSspli 1.36

**Comment by krisatjamf** [comment]
i've experienced this crash as well, my particular Wii U seems to have trouble staying connected to wifi, so i have lots of experience with intermittent connectivity.  generally i get hard lockups a few minutes after successfully retrying from the red-screen-of-doom.

i have not encountered a lockup on the red-screen-of-doom.

earlier today i encountered the "wii U makes a buzzing sounds while hard locked up". i didn't investigate where the sound was coming from for fear of leaving in that state causing damage to my wii

**Comment by krisatjamf** [comment]
> i've experienced this crash as well, my particular Wii U seems to have trouble staying connected to wifi, so i have lots of experience with intermittent connectivity. generally i get hard lockups a few minutes after successfully retrying from the red-screen-of-doom.
> 
> i have not encountered a lockup on the red-screen-of-doom.
> 
> earlier today i encountered the "wii U makes a buzzing sounds while hard locked up". i didn't investigate where the sound was coming from for fear of leaving in that state causing damage to my wii

i've also noticed that after bouncing the hardware the files downloaded to disk (either SD or UDB HD) are not able to be resumed, in the case of one download which got to around 3 out of 4 GB, the directory on my HD was totally gone.  how often do you sync out to disk, or what would cause the entire directory to be completely gone?

**Comment by V10lator** [comment]
> what would cause the entire directory to be completely gone?

It seems that under some cirumstances the Wii U does a rollback of its properitary filesystems (so NAND and USB). This has probaby been done by Nintendo to prevent NAND corruption in case of some crashes but not sure what exactly triggers this rollback.

Other than that please note that this is a place to report bugs. Please use GBATemp or Discord for such support questions.

**Comment by V10lator** [comment]
Is this still an issue with v1.39?

**Comment by Adzetko** [comment]
Hi, I'm on V1.49 and it seems like this is still a thing
![IMG_20211205_172930](https://user-images.githubusercontent.com/18583615/144755380-9afbcdd8-f3d8-4c7b-9b0e-e0bd968c350a.jpg)
I mean, I don't know if it's the same issue or if I have to open a new thread? The error code isn't the same, but the error is here until I quit NUSspli. Tried on the WUP and Homebrew Launcher version, both with the same results.

**Comment by V10lator** [comment]
Please test one of these:
* https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.50-ALPHA1-Aroma-DEBUG.zip
* https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.50-ALPHA1-Channel-DEBUG.zip
* https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.50-ALPHA1-HBL-DEBUG.zip

**Comment by celsobonutti** [comment]
I’m also getting this, v1.54

**Comment by V10lator** [comment]
For all getting this freeze: Could you try to recreate it with the DEBUG build of NUSspli and this running on your PC: https://github.com/dimok789/loadiine_gx2/raw/master/udp_debug_reader/UdpDebugReader.exe ? That should produce a log which might help finding where exactly it freezes.

**Comment by Adzetko** [comment]
Seems to be working on 1.55, can't reproduce anymore. I keep the UdpDebug running in the background and will dump it here if it happens again.

**Comment by V10lator** [comment]
So I guess this is fixed. Reopen if not.
