### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Zaybomb** [V10lator/NUSspli#51]
Launching from home launcher 2.1 fix and it is black screening and going unresponsive as soon as I press load.

**Comment by Zaybomb** [comment]
Using the latest Nusspli

**Comment by V10lator** [comment]
Haxchi or Mocha?

**Comment by V10lator** [comment]
Also please test on of these:
* https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.42-ALPHA2-Aroma-DEBUG.zip
* https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.42-ALPHA2-Channel-DEBUG.zip
* https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.42-ALPHA2-HBL-DEBUG.zip

**Comment by LuckyDingo** [comment]
I'm also having the black screen error after updating to 1.41 HBL latest version.
Unfortunately, the 1.42-ALPHA2-HBL-DEBUG version you uploaded doesn't seem to fix the issue. Not sure how I can help, but if you want me to try a new test build or upload a logfile of some sort just let me know!

**Comment by V10lator** [comment]
Could you grab a log with this and the alpha build? https://github.com/dimok789/loadiine_gx2/raw/master/udp_debug_reader/UdpDebugReader.exe

Just run the exe on your PC and the alpha on your Wii U while having both on the same network.

**Comment by LuckyDingo** [comment]
Haxchi, all with Homebrew Loader, and the last working version I tried was 1.37.
1.41 and 1.40 gave me black screens, but 1.39 and 1.38 gave me this error screen:

There is a problem with the system memory.

For help, make a note of the error code and visit
support.nintendo.com.

Error Code: 160-2203
(1) 99.99.99 U (2) WUP-101(02) (3) FW402627737 (4) HBL0-0211-3775

And just tried 1.37 and it still works.

So do I start writing the log at the Homebrew Loader screen before opening NUSspli or after I open NUSspli?

**Comment by V10lator** [comment]
Please test: https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.38-ALPHA8-HBL-DEBUG.zip

**Comment by LuckyDingo** [comment]
NUSspli-1.38-ALPHA8-HBL-DEBUG worked fine. It asked me if I wanted to update to 1.41 and I pressed B to not update and it took me straight to the main menu, I pressed A to see if it would load the list of titles and that worked fine, so I exited the application.

I'm attaching the logfile to this comment.
[GeckoLog.txt](https://github.com/V10lator/NUSspli/files/7641742/GeckoLog.txt)

**Comment by V10lator** [comment]
Please test: https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.38-BETA2-HBL-DEBUG.zip

**Comment by Zaybomb** [comment]
> Haxchi or Mocha?

haxchi

**Comment by Zaybomb** [comment]
> Also please test on of these:
> 
>     * https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.42-ALPHA2-Aroma-DEBUG.zip
> 
>     * https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.42-ALPHA2-Channel-DEBUG.zip
> 
>     * https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.42-ALPHA2-HBL-DEBUG.zip

Still black screening

**Comment by V10lator** [comment]
I know it sais it is the same version but trust me: It's not. Please test file:///home/v10lator/git/NUSspli/zips/NUSspli-1.38-BETA2-HBL-DEBUG2.zip

Please also retest v1.39 as error 160-2203 should be fixed there.

**Comment by Zaybomb** [comment]
> Please test: https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.38-ALPHA8-HBL-DEBUG.zip

that is working

**Comment by LuckyDingo** [comment]
NUSspli-1.38-BETA2-HBL-DEBUG2 gives me a black screen.

logfile here:
[GeckoLog.txt](https://github.com/V10lator/NUSspli/files/7641856/GeckoLog.txt)

Going to try 1.39 now

**Comment by V10lator** [comment]
Please test: https://public.nbg01.v10lator.de/NUSspli/NUSspli-1.42-ALPHA3-HBL-DEBUG.zip

**Comment by LuckyDingo** [comment]
NUSspli-1.39-HBL-DEBUG just gave me a black screen.
logfile here:
[GeckoLog.txt](https://github.com/V10lator/NUSspli/files/7641908/GeckoLog.txt)

And NUSspli-1.39-HBL gives me a black screen as well... Huh. I must have been mistaken about 1.39. Sorry about that!

**Comment by LuckyDingo** [comment]
NUSspli-1.42-ALPHA3-HBL-DEBUG worked perfectly fine.

logfile here:
[GeckoLog.txt](https://github.com/V10lator/NUSspli/files/7641947/GeckoLog.txt)

**Comment by V10lator** [comment]
@LuckyDingo Could you contact me on Discord, please?

**Comment by LuckyDingo** [comment]
@V10lator Sure, what's your Discord contact?

**Comment by V10lator** [comment]
https://discord.gg/B8ZBd6mrnV
