### ISSUE TITLE
In-app update issue (might just be me)

### ISSUE THREAD

**Issue by Korozin** [V10lator/NUSspli#53]
so I'm not entirely sure if this is purely a problem on my end of the spectrum but everytime a new update is pushed and it gives the prompt to install in the app, whether it be HBL or Menu Channel it always fails. I've noted that it says apply sig-patches but that puzzles me because I have CBHC installed, sig patches are always applied in my system. Like I said I'm not sure if it's something specifically on my end but it seemed like an issue worth noting. Not an entirely big issue as I can just update it from the GitHub repo, but if it isn't just my end it's an error nonetheless. Anyways sorry for bothering, have a good day. PS I absolutely love your work, keep it up lol.

**Comment by V10lator** [comment]
Please open one issue for HBL and one for Channel. Make sure to add detailed error mesages to both.
