### ISSUE TITLE
Channel update error

### ISSUE THREAD

**Issue by Korozin** [V10lator/NUSspli#54]
I think you told me to open another one specifically for one of the subsections so I'll do it for the Wii U Menu one and be more detailed. So as I said before I have CBHC installed so Signature patches are always on. Once I open the app it says there's a new update available so I press A, it downloads and extracts perfectly, but at 98% in the installation process the screen will turn red and list "Please verify WUP files are correct" and right under it "DLC/E-Shop requires sig patch" which was already applied. I also tested it on my backup system without CBHC using both Haxchi CFW and 3 different versions of Mocha, all of which failed. (in hindsight it looks like the writing said I tried mocha ontop of haxchi which was not true, I tried them seperately)

**Comment by Korozin** [comment]
One thing I can think of to fix this however would be editing the NUSspil.txt in root and just turning off check for updates. If I'm right that would stop it from trying to update, or I could just update manually from here. Either way it's not a huge deal

**Comment by Adzetko** [comment]
I can confirm having the same issue on the WUP version of NUSspli

**Comment by Korozin** [comment]
> I can confirm having the same issue on the WUP version of NUSspli

I would suggest just editing the NUSspli.txt and changing `check for updates: true` to `false` as it fixes the issue if you don't want to update. Otherwise just update it manually from the github page.

**Comment by V10lator** [comment]
> I would suggest just editing the NUSspli.txt and changing `check for updates: true` to `false`

I wouldn't recommend editing the `sd:/NUSspli.txt` file by hand. All settings inside should be changeable from within NUSspli (most of them by pressing left on its main menu screen). If some option is missing, so you have no other way than changing the config file by hand, that would be a bug.

> it fixes the issue

It doesn't fix the issue, it disables functionallity and as a result hides the issue. ;) I also wouldn't recommend not doing any updates at all (disabling auto-updates and never looking at GitHub for manual updates, for example).

Other than that thanks for reporting. Most likely it's some error in one of the xml files here but I'm out of ideas, so if anyone sees an error please tell: https://github.com/V10lator/NUSspli/tree/master/meta/menu

**Comment by Korozin** [comment]
> > I would suggest just editing the NUSspli.txt and changing `check for updates: true` to `false`
> 
> I wouldn't recommend editing the `sd:/NUSspli.txt` file by hand. All settings inside should be changeable from within NUSspli (most of them by pressing left on its main menu screen). If some option is missing, so you have no other way than changing the config file by hand, that would be a bug.
> 
> > it fixes the issue
> 
> It doesn't fix the issue, it disables functionallity and as a result hides the issue. ;) I also wouldn't recommend not doing any updates at all (disabling auto-updates and never looking at GitHub for manual updates, for example).
> 
> Other than that thanks for reporting. Most likely it's some error in one of the xml files here but I'm out of ideas, so if anyone sees an error please tell: https://github.com/V10lator/NUSspli/tree/master/meta/menu

I know that it doesn't fix it and I didn't suggest never looking here. The only reason I suggested editing the file is if someone was too lazy to update manually here or just wanted to keep a specific version. Which I don't see why they would be as it takes 2 seconds. Anyways thanks for the response, and I like your work if I see a bug in the future I'll make a new issue.

**Comment by V10lator** [comment]
Please don't close open issues.

**Comment by LinkTheHer0** [comment]
> I think you told me to open another one specifically for one of the subsections so I'll do it for the Wii U Menu one and be more detailed. So as I said before I have CBHC installed so Signature patches are always on. Once I open the app it says there's a new update available so I press A, it downloads and extracts perfectly, but at 98% in the installation process the screen will turn red and list "Please verify WUP files are correct" and right under it "DLC/E-Shop requires sig patch" which was already applied. I also tested it on my backup system without CBHC using both Haxchi CFW and 3 different versions of Mocha, all of which failed. (in hindsight it looks like the writing said I tried mocha ontop of haxchi which was not true, I tried them seperately)

I have the same error, except that I use Haxchi, I went from 1.72 to 1.77 and I got that error, and the channel is corrupted, so I have to delete it, download it and install it again.

**Comment by V10lator** [comment]
@LinkTheHer0 and at all other readers: Yes, channel version has an update bug. That's known, we can't do anything against it so... Deal with it... Really sorry to say it that way but there's no way to tell it more softly.

In other words: For best auto-update results use HBL version or wait for Aroma CFW.

**Comment by V10lator** [comment]
We should have a workaround now.
