### ISSUE TITLE
search button off 1.69 and 1.70 freeze

### ISSUE THREAD

**Issue by daqueenqueen666** [V10lator/NUSspli#56]
when pulse Y for search the app freeze and need shoutdown the wii u y tested en hb version and channel version

**Comment by takoyaki99** [comment]
This issue happens to me from an update to 1.70.

**Comment by LinkTheHer0** [comment]
I have the same problem, i have the channel version.

**Comment by V10lator** [comment]
Thanks for the reports. What controllers are you using and are there any other controllers connected while this happens?

**Comment by LinkTheHer0** [comment]
> Thanks for the reports. What controllers are you using and are there any other controllers connected while this happens?

I am using the Wii U Gamepad and is connected the GameCube control adapter but there is no connected control

**Comment by takoyaki99** [comment]
Wii U gamepad. No remotes connected

**Comment by Xpl0itU** [comment]
Try this build
[NUSspli-1.71-ALPHA1-HBL-DEBUG.zip](https://github.com/V10lator/NUSspli/files/7793455/NUSspli-1.71-ALPHA1-HBL-DEBUG.zip)
[NUSspli-1.71-ALPHA1-Aroma-DEBUG.zip](https://github.com/V10lator/NUSspli/files/7793464/NUSspli-1.71-ALPHA1-Aroma-DEBUG.zip)
[NUSspli-1.71-ALPHA1-Channel-DEBUG.zip](https://github.com/V10lator/NUSspli/files/7793468/NUSspli-1.71-ALPHA1-Channel-DEBUG.zip)

**Comment by V10lator** [comment]
Thanks @Xpl0itU :)
Rest: Do what he said and report back if it works, please.

**Comment by takoyaki99** [comment]
Channel failed to install (using WupInstaller GX2). I’m new to the Wii U scene so I don’t know if you can overwrite titles with newer versions, but I’ve never had problems with it on my hacked Switch.
Homebrew Launcher version (launched from homebrew menu forwarder) doesn’t display anything normal, just a string of letters and buttons.
On a press of A on the Gamepad, some Japanese text comes up. It’s shop listings for random games, one seems to be something like “Tournament Karaoke” (although the text itself isn’t fully on screen so I can’t read what the full game name is).

First screen is what happens on bootup, second is what happens after an A press.

**Comment by V10lator** [comment]
@takoyaki99 There's indeed a known bug with channel reinstalls. For the time beeing please uninstall first.

For the rest of what you said: Sorry, am not at home so tried to review codes on my mobile phone, telling @Xpl0itU what to change in codes. Seems like this didn't work out through so you'll need to wait untill I get home again (next year).

**Comment by LinkTheHer0** [comment]
> Try this build [NUSspli-1.71-ALPHA1-HBL-DEBUG.zip](https://github.com/V10lator/NUSspli/files/7793455/NUSspli-1.71-ALPHA1-HBL-DEBUG.zip) [NUSspli-1.71-ALPHA1-Aroma-DEBUG.zip](https://github.com/V10lator/NUSspli/files/7793464/NUSspli-1.71-ALPHA1-Aroma-DEBUG.zip) [NUSspli-1.71-ALPHA1-Channel-DEBUG.zip](https://github.com/V10lator/NUSspli/files/7793468/NUSspli-1.71-ALPHA1-Channel-DEBUG.zip)

I have deleted the previous channel, downloaded the Channel version and when installing it with the Wup Installer GX2 I get the following message: "Verify WUP files are correct & complete. DLC / E-shop require sig patch."

**Comment by LinkTheHer0** [comment]
I have used the HBL version and it looks like this on the screen 

![imagen](https://user-images.githubusercontent.com/52388368/147800030-59bf4c2c-0c2d-44ed-a953-a237f5d9c907.png)

**Comment by V10lator** [comment]
Thanks again, @Xpl0itU is working hard to fix this. No promises but maybe you'll get a new version to test later this day.

**Comment by Xpl0itU** [comment]
New builds, this should fix the rendering errors in alpha 1
[NUSspli-1.71-ALPHA2-HBL-DEBUG.zip](https://github.com/V10lator/NUSspli/files/7796209/NUSspli-1.71-ALPHA2-HBL-DEBUG.zip)
[NUSspli-1.71-ALPHA2-Aroma-DEBUG.zip](https://github.com/V10lator/NUSspli/files/7796213/NUSspli-1.71-ALPHA2-Aroma-DEBUG.zip)
[NUSspli-1.71-ALPHA2-Channel-DEBUG.zip](https://github.com/V10lator/NUSspli/files/7796215/NUSspli-1.71-ALPHA2-Channel-DEBUG.zip)

**Comment by takoyaki99** [comment]
Channel install failed, although that could’ve been because I assumed that NUSspli was gone because the title did not show up on my Wii U menu.
But HBL version works normally, downloads OK, search OK.

**Comment by V10lator** [comment]
Thanks for testing. Will review the codes of @Xpl0itU next days and draft a new release.l containing his fixes.

**Comment by liOnux-fr** [comment]
Hi,
I confirm this issue with v1.70-Channel : no on-screen keyboard when I use gamepad without other controllers.

**Comment by EeveeEuphoria** [comment]
Hey, I was getting this same issue, but the 1.71 Alpha 2 HBL version works for me. I'll edit this when I've tested the channel version in a bit, and report how that goes.

**Comment by liOnux-fr** [comment]
Hi,
These are my tests : 1.71 Alpha 2 HBL works, but not Aroma. And there is an sig patch error when installing Channel.
