### ISSUE TITLE
NUSspli 1.70 & Tiramisu, Installation fail

### ISSUE THREAD

**Issue by shuya070k** [V10lator/NUSspli#57]
Hi,
When i try to install games, it fails everytime. Error message says: "Installation failed. Verify WUP files complete. Paid content requires cfw." 
Tiramisu has been released yesterday, so I might think NUSspli is not compatible with it.

**Comment by V10lator** [comment]
NUSspli needs sigpatches which aren't contained in Aroma.
Anyway, the official installation guide at https://wiiu.hacks.guide offers https://wiiu.hacks.guide/docs/files/01_sigpatches.rpx so which guide did you follow?

**Comment by V10lator** [comment]
Forgot what I told above. Will be fixed with the next version.
