### ISSUE TITLE
Delete broken download in USB

### ISSUE THREAD

**Issue by Carl05Daniel** [V10lator/NUSspli#62]
A download got corrupted or something, even if I try to redownload it, it keeps getting stuck.

At the end, I downloaded it on the SD card instead and it worked. However, the installation files are still on the USB HDD and I cannot delete them.

Can you add an option to delete this broken files?

**Comment by Kojinesman344** [comment]
im in the same situation , im going to format the usb drive back in the wii u system settings and see where that leaves me with. also im trying to find a file explorer for the wii u and try to delete it that way

**Comment by Masamune3210** [comment]
Ftpii-Everywhere should be able to access mounted drives, but honestly its better to just format the drive if you have nothing else on it as deleting files doesn't always delete the references to it in the system which can get messy fast

**Comment by V10lator** [comment]
Files should no longer be able to corrupt with v1.82. See #80 for more informations.

**Comment by TheAvacad0** [comment]
> Ftpii-Everywhere should be able to access mounted drives, but honestly its better to just format the drive if you have nothing else on it as deleting files doesn't always delete the references to it in the system which can get messy fast

Brick messy?
