### ISSUE TITLE
Back to search results

### ISSUE THREAD

**Issue by liOnux-fr** [V10lator/NUSspli#63]
Hi, I have a question about this great tool :
Once the download of a title is finished (the screen turns green :-) ), I would like to go back to my previous search results.
But when I press the "B" button, the home screen is displayed and my search result is lost.
What is the way to get back the previous search results ?

**Comment by V10lator** [comment]
This is not a place to ask questions. For this go to [GBATemp](https://gbatemp.net/threads/nusspli-install-content-directly-from-the-nintendo-update-servers-to-your-wii-u.566055/) or [Discord](https://discord.gg/B8ZBd6mrnV), please.

**Comment by liOnux-fr** [comment]
I'm sorry but it's because the label "**need more infos**" may be use here.
Anyway, I will ask my question to GBATemp.
Thanks
