### ISSUE TITLE
Internal error installing

### ISSUE THREAD

**Issue by mattcoad** [V10lator/NUSspli#64]
I tried to install super mario bros 3 eur and got the following error.
Install to wiiu formatted usb drive.

Internal error installing: 
Your homebrew channel is probably outdated..

Check and my homebrew channel is latest 1.5

**Comment by V10lator** [comment]
Sadly this is a bug in Tiramisu. To work around this please install and use https://github.com/GaryOderNichts/homebrew_launcher/releases/tag/v2.1_fix

After installing the 2.1 fix you'll face another Tiramisu bug through: .rpx homebrews will crash except you launch a .elf homebrew before (CC @GaryOderNichts ). To work around this remove the file `wiiu/environments/tiramisu/modules/setup/50_hbl_installer.rpx`. This will remove HBL 1.5 from Mii Maker which should be no big deal as you installed HBLC v2.1 fix already.

**Comment by mattcoad** [comment]
how do i install that version from the current installed version using Tiramisu?

**Comment by V10lator** [comment]
We're currently testing a workaround which uses Tiramisu technology to break out of HBL.

**Comment by V10lator** [comment]
Fixed with v1.74.
