### ISSUE TITLE
NUSspli does not honour configured proxy

### ISSUE THREAD

**Issue by eku** [V10lator/NUSspli#65]
A proxy is configured in my Wi-Fi profile. But NUSspli establishes a direct connection and then reports an error that it cannot download the JSON file.

On the firewall you can see that a direct connection to nbg01.v10lator.de:443 should be established.

Version: NUSspli-1.72-HBL.zip

**Comment by V10lator** [comment]
I'm sorry but at the time of writing [WUT](https://github.com/devkitPro/wut) doesn't offer a way to read out proxy settings.

**Comment by eku** [comment]
I am confused about your statement because the downloads from the NUS use the proxy.

**Comment by eku** [comment]
Hi @V10lator,
I understand the commit https://github.com/devkitPro/wut/commit/159f578b34401cd4365efd7b54b536154c9dc576 from Maschel to mean that the functionality is now available, but nevertheless nusspli still does not work h
