### ISSUE TITLE
Allow installation of downloaded titles from USB to NAND/USB without deleting from USB

### ISSUE THREAD

**Issue by vxbinaca** [V10lator/NUSspli#66]
I want to archive my purchased games from the eshop so I don't have to deal with the SLOW downloads from NUS. I want a local mirror of the downloads. Currently NUSspli warns it will delete from USB.

Version: 1.72 Channel

Edit: Thank you for this tool by the way it's much appreciated. I see you doing 4 releases a day. It's appreciated.

**Comment by V10lator** [comment]
The thing is it's not us but MCP (a tool by Nintendo) installing the titles. We're doing this exactly like the eShop. Now we're also not deleting the files from USB or MLC: This is hardcoded into MCP.
It's just that MCP was never designed to install from the SD card, so there seems to be a bug not deleting the files which we use to, well, keep the files on SD.
