### ISSUE TITLE
Download Progress runs out of the picture on the right

### ISSUE THREAD

**Issue by eku** [V10lator/NUSspli#67]
Either the bars are shortened or the decimal places are deleted.

**Comment by V10lator** [comment]
Could you show a screenshot, please, as I can't really imagine what you descibe. Also what title ID are you trying to download?

**Comment by eku** [comment]
![c](https://user-images.githubusercontent.com/418685/149627518-ae1113de-40b2-4c19-9a6f-1e87455e26eb.jpg)

**Comment by V10lator** [comment]
Ah, now I see. Thanks, will have a look into ist soon. Title ID would still be nice to know through.

**Comment by V10lator** [comment]
Can't confirm as I can't find a title with a 6 digit filesize and you still refuse to tell the title ID you used but should be fixed with v1.76.

**Comment by eku** [comment]
@V10lator try `Trine Enchanted Edition (EUR)`.

**Comment by V10lator** [comment]
Thanks again. From seeing it now I agree that moving it even more to the left will look bad. I don't think removing a decimal place is a good idea as there are games multiple GB in size (where the decimal places are updating slow already. Removing one would make it so slow, the user might incorrectly think the download froze).

Anyway, while it looks weird now I'll consider it a minor issue as everthing is visible on screen and there don't seem to be many games with a 6 digit filesize.
