### ISSUE TITLE
Unified screen output for Gamepad screen and HDMI output

### ISSUE THREAD

**Issue by Roet-Ivar** [V10lator/NUSspli#7]
As a suggestion for making life easier would be to have the exact same info on the Gamepad screen as the HDMI output, the kicker is that you could then opt for navigate using regular controllers later on, the virtual keyboard has D-pad support.

**Comment by V10lator** [comment]
All UI is drawn to both screens except the keyboard (in case I'm wrong please tell me as this would be a big bug) and there I'm not sure about how to draw it to both screns as all I do is:
```
void drawKeyboard()
{
	colorStartNewFrame(bgColor);
	
	renderer->prepareDrcRendering();
	window->draw(renderer);
	Swkbd_DrawDRC();
	renderer->drcDrawDone();
	
	renderer->prepareTvRendering();
	window->draw(renderer);
	Swkbd_DrawTV();
	renderer->tvDrawDone();
	
	clearFrame();
	showFrame();
}
```

`Swkbd_DrawTV()` and `Swkbd_DrawDRC()` are just C wrappers for https://github.com/devkitPro/wut/blob/master/cafe/swkbd.def#L14 . Maybe sime expert like @GaryOderNichts knows the answer but I guess he won't help here. So will have a look for myself (by reviewing Garys patches for other homebrews) after the first public release.

**Comment by Roet-Ivar** [comment]
@V10lator yeah he's surely the expert when it comes to controller implementations!
