### ISSUE TITLE
Everything I download and install says it's corrupted. 

### ISSUE THREAD

**Issue by MastrLnk** [V10lator/NUSspli#71]
I'm updated to latest tiramisu and NUSspli. I've tried Channel install and hombrew. I've tried NAND, USB, and SD card download and the install always goes to red screen saying corrupted data.

**Comment by V10lator** [comment]
What's the exact error message? Also make sure you didn't forget the sigpatches from https://wiiu.hacks.guide/#/tiramisu/sd-preparation

**Comment by V10lator** [comment]
Am in a mad mood right now, so closing this cause you forgot to install sigpatches. Feel free to reopen in case I'm wrong.

**Comment by MastrLnk** [comment]
Sorry for not being clear. The error is "Installation failed! Possible corrupted files. Paid content requires a CFW." I've reinstalled everything following the guide perfectly including sigpatches. I tried another sd card, hdd, updated everything.  I tried wifi and wired connection. I can download on eShop fine. It seems to corrupt data at download because wup installer can't install it either.
