### ISSUE TITLE
Application 1.77 don't search

### ISSUE THREAD

**Issue by LinkTheHer0** [V10lator/NUSspli#75]
Hello, I just updated NUSspli to version 1.77 to install (not to use in SD) and I see that it does not search, the screen appears, but it does not recognize the touch screen, so it does not allow writing. 

![imagen](https://user-images.githubusercontent.com/52388368/151723931-71e883c1-6002-4343-8c08-8bf92d2c71b7.png)

**Comment by V10lator** [comment]
Hi and thanks for your report. Could you please give a bit more informations through? Like:
- What version did you update from?
- What controller are you using to navigate NUSspli?
- Do you have any other controllers connected while this happens and if so: Which and how?

**Comment by LinkTheHer0** [comment]
I have updated with the following:

NUSspli-1.77-Channel.zip

I just tried and now it works normally, I'm trying to replicate the error and I've noticed the following:

If I enter when a Wiimote (is with a nunchuk) connected, that's when the browser does not work.

**Comment by V10lator** [comment]
> If I enter when a Wiimote (is with a nunchuk) connected, that's when the browser does not work.

The keyboard works either with the DRC or other controllers only, depending on what you used last. That's a restriction by Nintendo.
