### ISSUE TITLE
[Tiramisu] Can't launch on Tiramisu "Don't run the EnvironnementLoader twice"

### ISSUE THREAD

**Issue by TxMat** [V10lator/NUSspli#76]
I have recently installed tiramisu with the autobooting and when i try to launch NUSspli from the HBC something funky is going on and i am welcomed with the message from Tiramisu saying that the environment should not be launched twice and that we need to open Mii Maker to run HBC again

I tried to look into other issues to see if someone already reported that because it seems to be a problem to all tiramisu users but i didn't see anything

maybe it's on my side and I'm doing something wrong but it really seems to be a NUSspli problem

if you need more details or something else ask and I'll be pleased to provide them

**Comment by V10lator** [comment]
Hi and many thanks for your report.

Are you using NUSspli Channel or HBL version and if HBL: Which HBL (like HBL 1.5 integrated into Tiramisu or HBLC 2.1 fix by Gary) are you using?

Other than that CCing @Maschell and @GaryOderNichts as this sounds like a issue with Tiamisus API we use for jailbreaking ( https://github.com/V10lator/NUSspli/blob/master/src/jailbreak.c#L70 ).

**Comment by TxMat** [comment]
I am using the HBL version of NUSspli laucched from the integrated 1.5 HBL 

I saw that the channel have some Updates so i decided to stick with the HBL ver (however i did not test the Channel version i'll try it right now and i'll let you know about it) 

i'll also try to launch NUSspli using HBLC 2.1 fix to see if the 1.5 ver is the problem

**Comment by V10lator** [comment]
No need to test NUSspli Channel or HBL version on 2.1 fix: I'm pretty sure this is a bug in Tiramisu and am again pinging @Maschell and @GaryOderNichts - To you two: This is the line of code failing: https://github.com/V10lator/NUSspli/blob/master/src/jailbreak.c#L70 - There's no way it fails on NUSsplis end but must be on Tiramisus, right?

**Comment by TxMat** [comment]
okay so here is the tests results : 

HBL 1.5 : 
 - [ ] working

HBL 2.1 fix (https://github.com/GaryOderNichts/homebrew_launcher/releases/tag/v2.1_fix) : 
 - [x] working

Channel Version : 
 - [x] working
 
so it may not me a tiramisu problem but more like a hbl 1.5 (tiramisu ver ?) problem 

do you think i should move the issue to the hbl git or the ping is enough ?

**Comment by Maschell** [comment]
> There's no way it fails on NUSsplis end but must be on Tiramisus, right?

When the target is not found it fallback to original .rpx (which would be the PayloadLoader). So I guess the `wiiu/apps/NUSspli/NUSspli.rpx` is not on the sd card

**Comment by V10lator** [comment]
> So I guess the `wiiu/apps/NUSspli/NUSspli.rpx` is not on the sd card

Thanks for the heads up. I didn't even think about this... @TxMat did you install NUSspli like you should do or followed some random youtube video?

**Comment by V10lator** [comment]
> okay so here is the tests results

Which aren't necessary as the problem has already been tracked down to the jailbreak codes used on Tiramisu HBL 1.5 only.

> the ping is enough ?

As you see a ping is more than enough. Please don't open bug reports at other projects as long as we don't tell you to do so.

**Comment by TxMat** [comment]
> > So I guess the `wiiu/apps/NUSspli/NUSspli.rpx` is not on the sd card
> 
> Thanks for the heads up. I didn't even think about this... @TxMat did you install NUSspli like you should do or followed some random youtube video?

Oh, I didn't know that the folders names were important so I just named the folder "NUSs" and put the rpx and the rest of the files in it as I thought it wouldn't change anything.

I'll rename the folder accordingly and see if the problem is now fixed

**Comment by TxMat** [comment]
It indeed works now. Thank you.
