### ISSUE TITLE
SSL red screen errror

### ISSUE THREAD

**Issue by jalopezsuarez** [V10lator/NUSspli#79]
![8C0AB443-A3B7-4448-81E6-3AEDA02790CB](https://user-images.githubusercontent.com/280283/153746539-99b7de66-813f-4b61-bc5b-fae11087b1fe.jpeg)

Hello, I have latest version Tiramisu. And latest version of Nusspli 1.78.

When I launch Nuspli I got SSL verify error but when I push B Button 2 or 3 times I can access  to blue screen. 

my system date and time is right.  how to fix this??

**Comment by V10lator** [comment]
> my system date and time is right.

Please double check this. Also show a screenshot of date and time settings.

**Comment by jalopezsuarez** [comment]
Yes!! You was right. Thanks!!
