### ISSUE TITLE
Multi-controller support

### ISSUE THREAD

**Issue by Roet-Ivar** [V10lator/NUSspli#8]
All controller support would be great if https://github.com/V10lator/NUSspli/issues/7 gets implemented!

The outcome would be that we wont have to rely on dying gamepads in the future.

**Comment by V10lator** [comment]
It might be a good idea to request that from @GaryOderNichts ( https://gbatemp.net/threads/homebrew-controller-mods-use-homebrew-gamepad-free.563011/ ) after the first public release has been done. Just don't be mad at him if he won't help. He's a genius and everyone should understand why he doesn't want his name associated with a tool like NUSspli.
