### ISSUE TITLE
Organize Titles Alphabetically by Title Name

### ISSUE THREAD

**Issue by sionisaac** [V10lator/NUSspli#82]
It's probably been asked already but is it possible to sort in alphabetical order?  If not could this be added as a feature?
Also another feature request would be the ability to launch installed titles from inside the app.  I gather that from March next year downloading from NUS servers is going be impossible.  Adding the ability to launch titles will ensure the app's usefulness past that date as it could also be used as a WiiU Menu replacement for peaople with more than 300 titles installed.

Just a suggestion.  Keep up the awesome work.

**Comment by V10lator** [comment]
> could this be added as a feature?

Not sure right now, so will reply to that later.

> I gather that from March next year downloading from NUS servers is going be impossible.

We don't think so as Nintendo sais you will still be able to download already purhased content. So the NUS should stay online, just no more way to purchase content.

> it could also be used as a WiiU Menu replacemen

https://github.com/wiiu-env/launchiine might be the better choice.

**Comment by sionisaac** [comment]
Launchiine may eventually be a better menu replacement but Maschell does not seem to be actively working on it (I guess his concentration is focused on Aroma).  How difficult would it be to add code to launch installed titles?  You already have the UI, menu system and list of installed titles.  Also Alphabetizing the title list could be done by storing the complete title list as an external file on SD/NAND/USB and bubble sorting the list by title name/app type/region etc.  If the list exist on next run of NUSspli display titles based on the order of the list.  If the list file does not exist generate a new one.

I have very limited skills with C/C++ else I would have a go at coding this myself.
