### ISSUE TITLE
Nusspli Hostname error

### ISSUE THREAD

**Issue by guill3sm** [V10lator/NUSspli#88]
Using latest versión of Nusspli, and trying yo install any game, an Network error appears ( Couldn't resolver hostname ) idk exactly which is the problem here. Using 1.84

**Comment by Zyliqx** [comment]
Hi! I don't know much about this error but i think you are trying to connect to a hostname that cannot be resolved to an IP address. Maybe try to look in the internet settings to see if you have entered something wrong.

**Comment by guill3sm** [comment]
> Hi! I don't know much about this error but i think you are trying to connect to a hostname that cannot be resolved to an IP address. Maybe try to look in the internet settings to see if you have entered something wrong.

Already checked and is not that the problem

**Comment by V10lator** [comment]
The Wii U has weak WiFi, so I gess that's the real issue. What you could do:
- Switch to a LAN adapter.
- Enable auto-resume in NUSsplis settings.
- Move the Wii U closes to the router.
