### ISSUE TITLE
"Couldn't load config file"

### ISSUE THREAD

**Issue by customswitch** [V10lator/NUSspli#89]
When I try to open NUSspli I get this error. The problem is that my SD Card isn't read only. How to fix it?

**Comment by V10lator** [comment]
Your SD card is write locked.

**Comment by customswitch** [comment]
Have you read my problem? The SD card isn't write locked. I can use it with my pc without any problems. There is nothing write locked.

**Comment by customswitch** [comment]
@V10lator I already tried it with different SD cards, and I'm still struggling with this error message. My SD card couldn't be write locked. Then it must be a software issue.

**Comment by V10lator** [comment]
A software issue is highly unlikely when you're the only one experiencing this and the Wii U loves to move the writelock switch just enough to make the card read only while inserting. Anyway: Are you able to create files with Wii U FTP server and do these files survive a reboot?

**Comment by customswitch** [comment]
No, I can't copy files with FTPiiU everywhere. So, you are right, my SD card is write locked. This cannot be the problem. I tried more than 10 times to plug the SD card intro my console. But on my PC, everything is working fine.
