### ISSUE TITLE
one piece unlimited world red wii u freezing screen!

### ISSUE THREAD

**Issue by deppcreed** [V10lator/NUSspli#91]
After I download the One piece game, the game crashes on the screen. the game does not open. I downloaded from usbhelper and got the same error, needing to force shutdown.

**Comment by V10lator** [comment]
Doesn't sound like a bug in NUSspli and this is not a place to ask for support.

**Comment by deppcreed** [comment]
but I used NUSspli to download the game. another error I encounter, a red screen appears every time I try to download or install xenoblade chronicles x through nusspli.

**Comment by Masamune3210** [comment]
If you downloaded from usb helper and got the same result it isn't caused by WUPDownloader, something is up with your environment

**Comment by deppcreed** [comment]
I haven't used the usb helper to install xenoblade yet. I will try and I will bring information.
