### ISSUE TITLE
No error message at I/O queue write errors

### ISSUE THREAD

**Issue by NekoLoveFan** [V10lator/NUSspli#92]
I enter the application normally, everything is fine, I search for the game and start downloading it to the NAND, when it reaches 50% or more the console freezes even though it has enough storage, as with Zelda Wind Waker HD, having 4GB free, an error occurred error and then it freezes, it also happens to me with Zelda BOTW, which says that it occupies 9.53GB, I start the download in the NAND with 13GB free and when it reaches 70% it freezes and even in one of the freezes it did not exceed 10% download and had already frozen.
In this photo it is the 5th attempt (Zelda BOTW) and it still does not exceed 10% download and it get already gave a error, and just when the retry counter reached 1 the console froze leaving a annoying beep.
It is the versión 1.87 (The most recent that is available)
![20220418_161204389](https://user-images.githubusercontent.com/103899187/163886748-c3ef7162-ff8d-4157-92a6-f873c82b9166.jpg)

**Comment by V10lator** [comment]
Sounds like your NAND starts to have issues. So a hardware defect.

So will keep this report open but only for the bad error message (should give more details).

**Comment by CristianOrtega97** [comment]
Hello there, I am facing the same issue and I barely downloaded few items minutes ago. Any way to solve it?
