### ISSUE TITLE
More of a question than an issue.

### ISSUE THREAD

**Issue by Immortql** [V10lator/NUSspli#93]
I apologize for asking this on Github, I know this is for issues not questions but I am unable to access things like Discord in order to ask these questions, so I apologize if this causes any inconvenience. So my question is take this hypothetical situation, you only have 16 gigs left on your NAND, and you want a game that's 15 gigs, since the WUP files are 15 gigs would you need extra space for it to install as well? Or is only that amount of initial space needed for the download? For example if you were downloading an 8 gig game would you need 16 gigs free for the install? I know that it deletes the files after installation if they're downloaded to NAND or USB but does that space affect anything during install? Sorry if this is a dumb question but I've only just recently entered modding and I dont always fully understand how everything works.

**Comment by V10lator** [comment]
> you want a game that's 15 gigs, since the WUP files are 15 gigs would you need extra space for it to install as well?

AFAIK MCP deletes the .app files while installing, so you won't need 30 GB but surely more than 15 (around 19 GB free should work). This statement includes a lot of guessing through, so take it with a grain of salt.

For further questions use Discord (signing up there is simple) or GBATemp, please.

P.S. Neither downloading nor installing to NAND are recommended: The Wii U is EOL, so you want to higher the lifetime of the NAND by not using it (else this happens: https://github.com/V10lator/NUSspli/issues/92 - and from there on it's only a question of time untill the Wii U bricks completely). That said a USB HDD is highly recommended.

**Comment by Packjackisback** [comment]
it will quit saying it's out of space
