### ISSUE TITLE
Black screen followed with Goodbye screen on Haxchi

### ISSUE THREAD

**Issue by reiserfs** [V10lator/NUSspli#95]
Hello i tried on my WiiU with haxchi, loading from the HBC, i got a black screen then a goodbye screen and back to HBC, tryied 1.88 and 1.87 with and without DEBUG.

**Comment by V10lator** [comment]
Please make sure the .rpx file is at the correct location (sd:/wiiu/apps/NUSspli/NUSspli.rpx). NUSspli needs to reload itself to break out of HBL cause of a HBL bug but it sounds like it can't find the .rpx file.

**Comment by reiserfs** [comment]
the path was right, i got the channel version and installed with wupinstaller, but got the same problem, can be a Haxchi problem?

**Comment by V10lator** [comment]
We support Tyramisu only. Anyway, you should get a red error screen telling you exactly that instead of just exiting.

Could you try to run https://github.com/dimok789/loadiine_gx2/raw/master/udp_debug_reader/UdpDebugReader.exe on your PC while running a NUSspli DEBUG build on the Wii U, please? You should get a log inside of the exe that way.

**Comment by reiserfs** [comment]
`Fri 22 Apr 2022 09:27:49.910    NUSspli 1.88
Fri 22 Apr 2022 09:27:49.915    APD enabled by sys settings: false (0)
Fri 22 Apr 2022 09:27:51.944    SDL initialized!
Fri 22 Apr 2022 09:27:51.988    Stopping background music
Fri 22 Apr 2022 09:27:52.400    SDL closed
Fri 22 Apr 2022 09:27:52.400    Clearing screen log
Fri 22 Apr 2022 09:27:52.401    Shutting down filesystem
Fri 22 Apr 2022 09:27:52.401    main: Checking thread stacks...
Fri 22 Apr 2022 09:27:52.402    main: 0x00004924/0x0000FFF8
Fri 22 Apr 2022 09:27:52.402    Bye!
`

i will look forward to change to tiramisu, i do not have a big SD card now to make a NandDump with my. So i just ordered another on amazon and will wait till get a new one to move to Tiramisu.

**Comment by V10lator** [comment]
Thanks for the log. It seems everything works correctly untill it should show the CFW error but then skips this error screen.
Am not at home right now to check codes more closely but you don't press any button before the goodbye screen, du you? Just asking cause the error screen is the fist time the input gets readed and it's "press any button to exit".

**Comment by reiserfs** [comment]
No i do not press any button, i just load (from HBC) or from the NUSspli channel and wait, get black screen for 3~4 seconds, and goodbye screen.
The steps:
1 - turn on wiiu
2 - start Haxchi
3 - start HBC
4 - load NUSspli from HBC

Or
1 - turn on wiiu
2 - start Haxchi
3 -  start NUSspli from WiiU menu.

**Comment by V10lator** [comment]
Closing cause of no more replies after a potential fix had been pushed. Feel free to reopen in case this is still an issue.
